### ISSUE TITLE
Any plans to continue?

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-contrib/b#1]
Hi @serundeputy!

Do you have any plans to continue or you abundant it in favour to drush ?

I want to move it forward.
Also I was thinking about name and 'console' looks more as purpose related.

What do you think ?

**Comment by serundeputy** [comment]
thanks @Gormartsen!

I say we call it `backdrop console` and have `b` be the recommended way to launch it from the command line like in the readme:

```
make an alias to b
open your .bash_profile file
add a line (at the end is fine) like this alias b='php /path/to/b/b.php'
reload your bash profile: source ~/.bash_profile
```

I'm not hard set on that, but it is an idea; At the top of the README.md we could say something like `b ~ Backdrop Console` speed up your development and deploy cycles.

Just spit balling, but I definitely like the use of the word console in some way to clarify what the tool is for.

What do you think about `Backdrop Console`?

**Comment by Gormartsen** [comment]
`Backdrop console` perfectly describe purpose for this project!

**Comment by Gormartsen** [comment]
Closed as resolved.
