### ISSUE TITLE
$_SERVER https typo?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#104]
```php
if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
  // Ensure that any and all environment variables are changed to https://.
  foreach ($_SERVER as $key => $value) {
    $_SERVER[$key] = str_replace('http://', 'https://', $_SERVER[$key]);
  }
}
```
(Source: https://github.com/backdrop-contrib/b/blob/1.x-1.x/b.php#L144)

Is it just me, or should that last line instead be:
`$_SERVER[$key] = str_replace('http://', 'https://', $_SERVER[$value]);`
(e.g. change the last `$key` to `$value`)?

**Comment by indigoxela** [comment]
@BWPanda you're probably right, it should have been `$value`

But I wonder, why it's there anyway, as the host is hardcoded to localhost...

**Comment by ghost** [comment]
I'm not very familiar with this sort of thing, but is it possible that something else adds to `$_SERVER` and then this code updates `http` to `https`? If not and the `foreach()` just affects the values above it, then we should remove this altogether probably.

**Comment by indigoxela** [comment]
There seems to be no command that needs http(s) in any way.

I might be wrong, but have currently no time to dig deeper. Hopefully it's not urgent. Or does this block you in any way?

**Comment by ghost** [comment]
Nope, this has been working fine (or wrongly) for ages, no urgent need to change it yet :slightly_smiling_face:

**Comment by ghost** [comment]
I decided to remove that whole HTTPS section. I use Lando, and it stores various http and https URLs in `$_SERVER`, e.g.:

```
"urls": [
    "https://localhost:49232",
    "http://localhost:49233",
]
```

So blindly replacing `http://` with `https://` would be confusing at best, and destructive at worst.
