### ISSUE TITLE
Consolidating storage variables

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#105]
Currently `b` has a global [`$elements`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/b.php#L17) array, constants for [`BACKDROP_ROOT`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/b.php#L89) and [`BACKDROP_SITE`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/b.php#L92), and static get/set functions for [`yes_mode()`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/common.inc#L152), [`is_debug()`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/common.inc#L165), [`backdrop_installed()`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/common.inc#L178), etc.
It also parses the input command, arguments and options [more](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/command.inc#L65) than [once](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/command.inc#L118).

I'd like to consolidate these into one place/type of storage. For example, if we have a global variable for `$elements`, let's use global variables for the other things too. Or if we want to use constants for `BACKDROP_ROOT`, etc., we could use one for storing the command as well (instead of re-parsing the input in [`b_get_command_name()`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/command.inc#L65)). Or if we decide that static get/set functions are the way to go, let's use those for `$elements` and other things too.

I've thought of a few different ways to do this, but I'm not sure what the best option is...

**Global variables**
Global variables are easy to use and can store any type of data. You can get their values easily, and set them too (even adding to arrays). The annoying part is having to declare `global $variable1, $variable2, etc.` at the top of each function where you need to use them. And since initialising and documenting all of them could take up a lot of space (in terms of the number of lines of code/comments), maybe doing so in a new `globals.inc` file would be cleaner...?

**Constants**
We already have some constants (`BACKDROP_ROOT` and `BACKDROP_SITE`), so adding more would be easy enough. The main problems with constants is that they can't store arrays (only strings, booleans, etc.) (well, they can from PHP v7 onwards, but we still need support for PHP v5), they can't be changed once set (hence the name), and I often get warning about not using `'` around constant names (I'm always confused by when I need to do this or not). So I think constants are not really an option. Point is, if we're not using them for everything, should we use them for anything...?

**Static get/set functions**
These are new to me, but from looking at the code I see how they work and they're kind of clever. E.g.:
```php
function b_backdrop_installed($set = NULL) {
  static $mode;
  if ($set != NULL) {
    $mode = $set;
  }
  return $mode;
}
```
If we were to use these instead of other options, my main question is: do we have a separate function for each variable (like `b_backdrop_installed()`), or do we have a global array `$storage` and then a single get/set function for that like so:
```php
function b_storage($name, $value = NULL) {
  global $storage;
  if (!array_key_exists($name, $storage)) {
    // Show error message.
  }
  if (!is_null($value)) {
    $storage[$name] = $value;
  }
  return $storage[$name];
}
```
Separate functions for each variable mean we can tweak the getting and setting as needed (e.g. [`b_messages()`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/common.inc#L66) allows you to set a `message` *and* a `type`), but also mean a lot of duplication for variables that just store a single, simple value (e.g. the boolean ones like `b_yes_mode()` and `b_backdrop_installed()`).

Before I started this issue, I was confused about the best option (pros and cons, performance, etc.). But after writing this all out I'm thinking that global variables look like the way to go... Unless anyone has other ideas/suggestions?

**Comment by indigoxela** [comment]
It seems to me, while you were writing the issue description, you already figured out the best way to go. :wink: 

I don't have strong feelings about storage design, any of your suggestions is fine. Just pick the one that makes most sense for you.
