### ISSUE TITLE
`b_find_tmp()` necessary?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#109]
We have a custom function [`b_find_tmp()`](https://github.com/backdrop-contrib/b/blob/1.x-1.x/includes/filesystem.inc#L114) that gets the temporary directory of the system, however I found PHP's [`sys_get_temp_dir()`](https://www.php.net/manual/en/function.sys-get-temp-dir.php) and I wonder why we don't just use that...?

**Comment by indigoxela** [comment]
> ... sys_get_temp_dir()

Which b_find_tmp() also seems to use...

I think there could be some code reduction / simplification. Perhaps `b` doesn't do that check efficiently now.

To my understanding there are three possibly different and possibly relevant temporary dirs:

1. Operating system (/tmp on Linux)
2. Current system user (something different from custom php.ini)
3. Backdrop setting file_temporary_path in system.core.json (could be something completely different)

**Comment by ghost** [comment]
Interesting that WordPress doesn't do a lot of the checks we do... https://developer.wordpress.org/reference/functions/get_temp_dir/

Will keep the function, but simplify it as part of refactoring in https://github.com/backdrop-contrib/b/issues/5
