### ISSUE TITLE
Add commands to import and export databases

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#113]
Lando has `db-import` and `db-export` commands. I'd like to add similar commands to `b`.

**Comment by alanmels** [comment]
See https://github.com/backdrop-contrib/bee/issues/129. You can already import and export databases.

**Comment by ghost** [comment]
Closing this as a duplicate of https://github.com/backdrop-contrib/bee/issues/129. Work for importing and exporting DBs will continue there.
