### ISSUE TITLE
`tput cols` doesn't work in Lando

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#115]
Table rendering in `b` relies on knowing how wide the user's terminal is (so it can do all the fancy wrapping and stuff). We get the terminal width using `exec('tput cols)`. This works great normally, but in Lando it only returns the one value of '256', regardless of the actual terminal width. This causes wide tables to get messed up.

I finally worked out that this is because of the virtualisation that Lando uses. The only way around it that I know of (so far) is to first run `lando ssh`, then run any `b` commands that render wide tables. It's not ideal, but I'm just noting this here in case it bites me (or others) in future 😄

**Comment by ghost** [comment]
Closing now, as this is just for future reference, and I don't think there's anything we can do to fix it. Can reopen if that changes though.

**Comment by yorkshire-pudding** [comment]
For the record, Lando fixed this recently
