### ISSUE TITLE
Broken pm command functionality after code refactoring

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#120]
**Broken functionality with pm and themes:**

`# b dl purple`
/tmp/purple60192266539de/purple.zi 100%[================================================================>] 129.19K  --.-KB/s    in 0.01s   

 [✔] `purple` was downloaded into `/var/www/crashburn/html/themes/purple`. 

`# b en purple`

 [✔] The `Pretty in Purple` theme was enabled. 

`# b dis purple`

 [i] The `Pretty in Purple` theme is already disabled. 

**Nope, it isn't. So I disabled it via UI, then:**

`# b dis purple`

 [✔] The `Pretty in Purple` theme was disabled. 

**It has already been, the message is misleading.**

<hr />

**Broken functionality with pm and modules:**

`# b dl realname`
/tmp/realname601923c022b6c/realnam 100%[================================================================>]  18.69K  --.-KB/s    in 0s      

 [✔] `realname` was downloaded into `/var/www/crashburn/html/modules/realname`. 

`# b en realname`

 [✘] Project `realname` could not be found. 

**Wrong, it really _is there_ in the modules directory. And b pm-list actually lists it correctly.
So I enabled the module manually, then:**

`# b dis realname`

 [✔] The `Real Name` module was disabled. 

Yes, that worked.

`# b pmu realname`
array_flip(): Can only flip STRING and INTEGER values!
 /var/www/crashburn/html/core/includes/install.inc:1016

 [✔] The `Real Name` module was uninstalled. 

**Nope, it still shows in the UI at admin/modules/uninstall.**

**Comment by ghost** [comment]
@indigoxela I've made a PR that should fix these issue for you. Are you able to test for me?

The "theme is already disabled" and "Can only flip STRING and INTEGER values!" bugs were typos that I found and fixed. The rest were because the list of projects wasn't being refreshed each time. I'd previously tried to only refresh that list when/as necessary, but it seems I need to do it at the beginning of each command regardless.

**Comment by indigoxela** [comment]
I downloaded the patch and after `git apply 122.patch` repeated my example commands from above. :+1: The problems are fixed!

Additionally I tested some commands with a multisite install. :+1: Works, too.

**Comment by ghost** [comment]
Thanks for the review @indigoxela! I've given you the 'Triage' role for this repo, so hopefully that means you can add/remove labels on issues now.
