### ISSUE TITLE
Alternate quote character for commandline output

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#121]
A feature request.

With the code refactoring backticks ``` have been chosen as quoting character.

While that does no harm, I'm not completely comfortable with it, because backticks have a special meaning in Linux shells - they usually *run* something.

Example b output:
```
[✔] `fooproject` was downloaded into `/var/www/whereever`.
```

Example Linux usage of backticks:
```
chown www-data `ls *.php`
```
(This runs `ls *.php` and feeds the output to the chown command.)

Alternative character suggestions:

```
»Fooname«
’Fooname’
˝Fooname˝
“Fooname”
```
@BWPanda is that worth considering?

**Comment by oadaeh** [comment]
All four of the alternate character suggestions are not keys on a standard 101/102-key PC keyboard layout (at least in the US, I'm not sure about other keyboard layouts for other ISOs). These are what is printed when the quote keys are used:
'Fooname'
"Fooname"

**Comment by indigoxela** [comment]
> All four of the alternate character suggestions are not keys on a standard 101/102-key PC keyboard layout

I'm aware of that, but the characters are available here on my Linux laptop (quertz layout) via "Alt Gr" plus key - might be different with your keyboard layout, though.

My keys:
```
“” ... bn
’ ... #
»« ... xy
```
However, I don't think it's really necessary, that these keys are easily available via keyboard - they're printed by "b".

I just feel uncomfortable with an output that could never get safely piped to a Linux command - that's the reason why I opened this issue. I'm also aware that b's output probably isn't usable for piping into commands anyway - that's why it's a feature request. :wink:

**Comment by ghost** [comment]
Here's a PR if anyone's able to test/review: https://github.com/backdrop-contrib/b/pull/123

**Comment by indigoxela** [comment]
Testing with 123.patch: I like these `'` a lot more than the backticks. :smiley: 

Example: ` [✔] 'simplify' was downloaded into '.../modules/simplify'.`

**Comment by ghost** [comment]
Thanks! Merged.
