### ISSUE TITLE
Rename --url option to --site and allow using site name instead of URL

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#125]
We currently have a `--url` option for specifying which multisite site a command should use. However, the word 'url' doesn't really indicate that this is for specifying a particular site within a multisite installation. Also, it'd be nice to be able to specify the site *name*, rather than the site *URL*.

For example, for this `sites.php` setup:
```php
$sites['site1.my-multisite-install.com'] = 'site1';
$sites['site2.my-multisite-install.com'] = 'site2';
```

We currently require this:
```
b --url=site1.my-multisite-install.com status
```

We could instead allow either of these:
```
b --site=site1.my-multisite-install.com status
b --site=site1 status
```

**Comment by indigoxela** [comment]
You're quick with breaking changes. :wink:

**Comment by ghost** [comment]
Yeah, `b` will always allow breaking changes, but I'm trying to do them all before releasing v1.0.0.
