### ISSUE TITLE
Add `php-eval` command

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/b#128]
`php-eval` "my_function()" 

from drush would be really helpful. It lets you accomplish almost anything, sort of the tool of last resort.

Aliases ev, eval, php:eval

**Comment by bugfolder** [comment]
This looks like a good simple first task here; I'll work on implementing it.

**Comment by bugfolder** [comment]
[PR created.](https://github.com/backdrop-contrib/b/pull/135)

**Comment by ghost** [comment]
I'm no expert, but isn't this dangerous?

> The **eval()** language construct is *very dangerous* because it allows execution of arbitrary PHP code. *Its use thus is discouraged.* If you have carefully verified that there is no other option than to use this construct, pay special attention *not to pass any user provided data* into it without properly validating it beforehand. 

Source: https://www.php.net/manual/en/function.eval.php

**Comment by bugfolder** [comment]
Yes, it's very dangerous! But the php-eval command (which uses `eval()`) is built into drush, and is extremely useful. And anyone who can execute php code from the command line can accomplish any malfeasance they want, with or without the assistance of b or drush.

**Comment by ghost** [comment]
> And anyone who can execute php code from the command line can accomplish any malfeasance they want...

What about users who can't execute PHP code, but can use `b`? Would this give them access/abilities they wouldn't otherwise have?

**Comment by bugfolder** [comment]
Maybe. (I'm no expert either.) Once they have the ability to mess with config, they can certainly get access to and change a lot of information. And when the [SQL commands are implemented](https://github.com/backdrop-contrib/b/issues/129), they'll be able to dump or muck about with the databases to their heart's desire.

I mostly fall back on the observation that the php-eval command (and its use of `eval()`, see `drush/commands/core/core.drush.inc`, line 1178) has been in drush for a really long time, and is present now, so I would presume that the Drupal folks went through this discussion and came to the conclusion that including it was worth it.

**Comment by bugfolder** [comment]
Heh. [This article on securing a Drupal website](https://internetdevels.com/blog/your-drupal-website-security-how-you-can-ensure-it) recommends using `drush php-eval` for one of the steps in their process.

**Comment by oadaeh** [comment]
> What about users who can't execute PHP code, but can use `b`?

Isn't `b` PHP code?

**Comment by quicksketch** [comment]
I don't think running PHP code is bad if you've already got access to `b` and (presumably) the command line. I think if you have server access, anything about application level access is a moot point. `drush php-eval` is definitely super dangerous but I've used it in a pinch many times. Also handy for doing quick operations that would be difficult to do via SQL, like updating a node value.

**Comment by ghost** [comment]
Thanks for the work on the PR @bugfolder. It's looking good. Now that I've just fixed tests and merged them into the main branch, can you please use them as a guide and add some for this new command?

**Comment by ghost** [comment]
Also, the PR needs to be updated now that we've changed `b` to `bee`. I can do this if you like, but wanted to ask first in case you preferred to...

**Comment by bugfolder** [comment]
Still struggling with being able to push (anything) to the branch. I'll keep working on it, but if you get tired of waiting, I'm fine with you proceeding.

**Comment by ghost** [comment]
Thanks for adding some tests @bugfolder. Are you able to add another test that checks that calling a Backdrop function works too?

**Comment by bugfolder** [comment]
Sure, will do.

**Comment by bugfolder** [comment]
Added.

**Comment by ghost** [comment]
Thanks @bugfolder! I made a few small changes to your PR for consistency with other commands/tests, then merged it.
