### ISSUE TITLE
Change the documented command name from `b`?

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/b#132]
I have two suggested project names:
- bcli 
- bbash

I like bcli, because it's short and means something - backdrop command line interface!  
bbash is also nice, with some cadence with the double 'b'.

**Comment by ghost** [comment]
Are these suggested replacements for the official title of this project (i.e. instead of 'Backdrop Console'), or for the command you type each time (i.e. instead of `b`)?

**Comment by Wylbur** [comment]
Sorry, I thought that rename the project was on the table.  I was just giving suggestions for a replacement for 'b'.  

Just pick a good one, it will last!

**Comment by ghost** [comment]
No problem @Wylbur. I've renamed the issue accordingly. We'd only be changing the *documented* command name, since users need to setup their own shortcut for running `b` (either by putting a symlink in `/usr/local/bin` or using a bash alias). Which means they can already call it whatever they want to. So this issue seems to just be about changing the documentation from refering to `b` to refering to another name for the command instead...

**Comment by Wylbur** [comment]
@BWPanda Just my opinion, but there will be confusion for new users.  The project name on Backdrop is 'b', the repo name is 'b', the command file itself is 'b.php'.  Before the meeting yesterday I had not hear the term 'backdrop-console'.  If we have a chance for some consistency, we should take it now, before the 1.0 release.  As you said in the meeting yesterday, we can still break everything because we have not released...

**Comment by ghost** [comment]
The name of the project is 'Backdrop Console', so I've updated the project node on B.org: https://backdropcms.org/project/b

**Comment by ghost** [comment]
@alanmels wrote me on Zulip to say:

> I know it's an old idea that you are probably not much fond of. But I wonder is there any chance for you to consider to actually rename the `b` command itself? Leaving it as `b` would complicate SEO for other people to easily search and find the tool. Also it is a bit confusing.

To which I replied:

> When you say "the `b` command itself", there isn't actually a `b` command. The script that people run is actually called `b.php`, which no one's going to type all the time, therefore they're going to create an alias for it on their machine. In which case they can call it whatever they want. As for SEO, people can and should be referring to `b` as "Backdrop Console" which is the project's actual name.

I think the issue here is that we use the term `b` to refer to this project, whereas we should be saying "Backdrop Console". Both 'in person' and in the code/documentation.

So I think the solution might be to remove references to `b` in the code/documentation, and make it more obvious that, when installing, people can call the script alias whatever they want.

We could then leave the project's/repo's internal name as `b` and the main script as `b.php`, or we can go one step further and change them to `bconsole` instead (`backdrop-contrib/bconsole` and `bconsole.php` respectively)...

That will hopefully alleviate all the confusion.

**Comment by alanmels** [comment]
@BWPanda tanks for summarizing. While leaving people to create their own aliases is a good idea I still think it would be best for the project for marketing purposes if besides human name of "Backdrop Console" it had little longer "command line" name. 

So "going one step further and changing it" relates more to my liking, however I think changing it from just `b` to `bconsole` would be the other extreme - going from too short to too long. Ideally three letter abbreviation would be  more appealing, aesthetic and convenient to tipe. 

I'm ready to totally ditch the Brush project if you'd like to take over the namepace on github.com/backdrop-contrib/brush. If you don't like the idea to renaming it to `brush` what about `bacon` that popped up once in another thread. There could be so many other variants like `bcl`, `bcn`, `bit` (as `git`), `bite`. 

The name, the length of the command line tool name may seem unimportant at first glance, however the character it brings will stick in minds forever, so while semantically it could anything and [stand for nothing](https://www.tecmint.com/dnf-next-generation-package-management-utility-for-linux/), it better has some character, some convenience and comfort to pronounce, to type and to cultivate.

**Comment by ghost** [comment]
Maybe we should advertise the project as:

> A Command-Line Interface tool to help maximise your productivity.

Then we can call it "climax" 😆

**Comment by ghost** [comment]
Or:

> A collection of command-line tools for Backdrop.

Called "ctools" 😁

**Comment by ghost** [comment]
In all seriousness though, I think I've come up with a name that I really like, that's short, that can be used as the project name as well as the command name, and that will serve as a historical reminder of the original name for this project...

**Bee**

We might even be able to come up with a cute logo/mascot.

**Comment by alanmels** [comment]
I absolutely love it, Peter! Be it really "bee". It'll be lovely to type and cultivate. Backdrop imagined as a hive with lot's of bees around it constantly working and making honey.

**Comment by indigoxela** [comment]
The naming thing again... I remember the "bacon - Backdrop Console" discussion - (not suitable for vegetarians :joy: ).

Bee sounds really nice (but there's a Drupal module with that name). Who would have thought that naming something is the hardest part. :laughing:

**Comment by ghost** [comment]
> but there's a Drupal module with that name

Doesn't look like that'll be an issue, since [that module](https://www.drupal.org/project/bee) is only for Drupal 8+. Even if that module were to be ported to Backdrop eventually, it can use a different name since an 'upgrade' path wouldn't be possible from D8 anyway.

**Comment by ghost** [comment]
`b` is now 'Bee'! Fixed in https://github.com/backdrop-contrib/bee/commit/e559074d9a507cb920a4c874eaa2cde94b6207c3
