### ISSUE TITLE
Consider namespacing global variables?

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/b#134]
Some of the global variables have fairly generic names (e.g., `$command`, `$arguments`, etc.), which creates the potential for collisions with downstream code that might also be using generically named global variables. Suggest that `b` globals be namespaced (e.g., `$_b_command`, `$_b_arguments`, etc.). This would also help people grepping for local variables that might have those generic names.

**Comment by ghost** [comment]
@bugfolder Can you please provide an example of the issue here, to help me understand it better...?

**Comment by bugfolder** [comment]
The [Backdrop coding standards](https://docs.backdropcms.org/php-standards#naming-conventions) says: "If you absolutely need to define global variables, their name should start with a single underscore followed by the module/theme name and another underscore."

So that would suggest using `$_b_my_global` instead of `$my_global`.

An example of a collision would be if a module developer created their own `global $command` variable in their main module file. Now, that would certainly be bad form, counter to Backdrop guidelines, but if they did, then that creates the potential for hard-to-diagnose errors arising from using the same global variable. And a developer creating custom code for a single site (versus a contrib module) can get away with doing things like that (until the namespace collision bites them).

I don't think this qualifies as a "bug", by any means; it's more like just being neighborly in not taking up the global namespace unnecessarily.

(Also, it looks like the Travis testing is complaining about something like that in the automated tests.)

**Comment by ghost** [comment]
Thanks for that link @bugfolder! I don't recall seeing that before. Now I'm wondering if we should use static variables in functions instead (as the docs suggest)... This was previously considered here: https://github.com/backdrop-contrib/b/issues/105 but I ended up going with globals because they seemed simpler. Had I know about this, static variables would have been the best solution.

Maybe we should change this before v1.0...

**Comment by bugfolder** [comment]
Looking at your analysis in #105, I think you hit the right balance with using actual global variables, versus all the extra overhead associated with the static variables approach. (And, after all, even Backdrop uses plain old globals in settings.php.) Namespacing them by adding the prefix `_b_` wouldn't add much extra baggage, would be a nice thing to do, and not too hard to implement with search-and-replace. (Another nice feature of the naming convention is that when you see a variable named that way, you know it's global, even without having to look for the declaration.) I'd be willing to put together the PR, but at the end of the day, it's your baby, your call.

**Comment by ghost** [comment]
@bugfolder I initially wanted to decide to just do things properly and setup static variable functions, and I started doing this. But it eventually got a bit complicated and I was having to decide between making things easy to understand/use, or optimising code and removing duplicated code blocks. So I decided to scrap that idea and just namespace the variables as you suggested. The commit above does this, so this should be all good now. The tests seem happy, so I don't think I missed anything...
