### ISSUE TITLE
b pmi <project>: warnings if .info field is blank, Requires and Required by are wrong

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/b#136]
Three problems with the `b pmi <project>` command:

* If there is no entry for a field item in the .info file, a PHP warning is issued. Fixable with `empty()` checks.
* Entries for "Required by" are shown as "Array, Array, ..." and array-to-string conversion warnings are issued. Fixable with `array_keys()`.
* Ditto for entries for "Requires".

[PR](https://github.com/backdrop-contrib/b/pull/137)

**Comment by ghost** [comment]
Thanks for this @bugfolder. Do you have an example where a module didn't have a 'name' value in the info file? Since they're required, I wonder if we should bother allowing for no value... The rest of your changes look good though.

**Comment by bugfolder** [comment]
Ah, I'd included that check to gracefully handle the case of a missing name (as might happen during development, or with a custom module), but I see that if the name field is missing from the .info file, Backdrop puts in the machine name. So that check isn't necessary; I'll remove it.

**Comment by ghost** [comment]
Made review of PR. Few small changes needed.

**Comment by bugfolder** [comment]
New [PR 144](https://github.com/backdrop-contrib/bee/pull/144).

Replaces [PR 137](https://github.com/backdrop-contrib/bee/pull/137).

**Comment by ghost** [comment]
Thanks for this @bugfolder. PR merged.
