### ISSUE TITLE
b help doesn't document any options

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/b#14]
`b` accepts `--root`, `--drupal`, `--debug` and a few other options.  These are not mentioned by `b help`.

**Comment by ghost** [comment]
Putting here as a note to myself for when I get to this later...

The global options I can see in my [refactored code](https://github.com/backdrop-contrib/b/issues/5) so far include:
- `--root`
- `--url`
- `--yes`, `-y`
- `--debug`, `-d`

**Comment by ghost** [comment]
Fixed pushed in above commit.
