### ISSUE TITLE
Add PHPCS checks

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#145]
We moved from Travis CI to GitHub Actions for automated code checks, but we left out PHPCS checking (coding standards). We should add this back in, but it'll be nice to not need to download the whole `coder_review` module. So waiting to see what happens with extracting the `coder_sniffer` part in https://github.com/backdrop/backdrop-issues/issues/3213...

**Comment by jenlampton** [comment]
Coder review already has some drush commands we may be able to support / repurpose. 
https://github.com/backdrop-contrib/coder_review/blob/1.x-1.x/coder_review.drush.inc

(see also related https://github.com/backdrop-contrib/bee/issues/190)

**Comment by indigoxela** [comment]
Things are easier, now we have backdrop-ops/phpcs:

- Checkout our phpcs standards, move out one dir
- Checkout bee
- Run phpcs

We should fix all current violations, though (there aren't many).

**Comment by indigoxela** [comment]
A PR is now available: #253, need to review myself, possibly tomorrow, as this was a very quick shot. :smirk:

**Comment by indigoxela** [comment]
Here we go, seems to work:

![phpcs-bee-annotations](https://user-images.githubusercontent.com/842066/206148219-82f44fa4-5641-46d1-b973-b37e3c3a7439.png)
