### ISSUE TITLE
Bee cget not finding the file

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#146]
As an example:

```
b cget files/config_99561fc0124aee57813656f47e5aa4f8/active/system.core.json 

 [✘] The 'files/config_99561fc0124aee57813656f47e5aa4f8/active/system.core.json' config file could not be found.
```
(I'm using a symlink b -> bee/bee.php)

Absolute path also doesn't seem to work:

```
b cget /var/www/crashburn/html/files/config_99561fc0124aee57813656f47e5aa4f8/active/system.core.json 

 [✘] The '/var/www/crashburn/html/files/config_99561fc0124aee57813656f47e5aa4f8/active/system.core.json' config file could not be found. 
```
Do I misunderstand something, or is this a bug? `ls -l` does find the file.

Version: Bee 1.x-1.0.0-beta snapshot.

**Comment by indigoxela** [comment]
Or just the name:

```
b cget system.core.json

 [✘] The 'system.core.json' config file could not be found. 

```
Or:
```
b cget system.core.json site_name

 [✘] 'site_name' could not be found in the 'system.core.json' config file. 

```

**Comment by ghost** [comment]
Try without '.json'

**Comment by ghost** [comment]
Basically you use this command the same way you use 'config_get()'...

**Comment by indigoxela** [comment]
That's not very comfortable IMO. If I have to lookup the files, then strip the path and extension, I'm a lot faster if I just open the file. :smile:

**Comment by indigoxela** [comment]
But confirmed - it works when I do both.

**Comment by ghost** [comment]
The filename is basically like a namespace for the config options. So this command just needs the namespace and, optionally, the option name. This is also how the 'config_*' API functions work.

So I'm tempted to close this as 'works as designed', but if you really want to use the actual filename and/or path as well, then feel free to make this a feature request and we'll see what others think...

**Comment by indigoxela** [comment]
> So I'm tempted to close this as 'works as designed', but if you really want to use the actual filename and/or path as well, then feel free to make this a feature request

Sure, no problem, let's close this. I probably won't make a feature request, just won't use the command, as it provides no special convenience over just reading the file. :smirk:
