### ISSUE TITLE
Show Bee's own version when running the "status" command

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#147]
For further requests or bug reports here in the queue it would be convenient, if Bee was able to output its own version (like currently 1.x-1.0.0-beta). Drush, for example, shows its version with the `st` command.

Not sure how complex that may be... Just throwing in an idea. :smiley:

**Comment by ghost** [comment]
Good idea. I think I hadn't bothered before because there wasn't an actual release.

**Comment by yorkshire-pudding** [comment]
Link to #203 and #197

**Comment by indigoxela** [comment]
Here we go: #227
