### ISSUE TITLE
Explore if can be deployed to shared hosting and if so provide instructions

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#152]
Have tested on my shared hosting and works.  Preparing a pull request for the readme file.

**Comment by ghost** [comment]
Considering the length of the new instructions, I'm wondering if putting them in the wiki would be a better idea...

Will review and get back to you.

**Comment by yorkshire-pudding** [comment]
> Considering the length of the new instructions, I'm wondering if putting them in the wiki would be a better idea...
> 
> Will review and get back to you.

@BWPanda I did wonder that but saw there wasn't a wiki there yet.

**Comment by ghost** [comment]
Yeah, wasn't a need for one previously.

After looking at the new README, I think the Installation section is way too long (main install instructions, Lando, then the new shared sections). I'll move it all to the wiki then put a link in the README. I'll also close the PR: https://github.com/backdrop-contrib/bee/pull/155

**Comment by yorkshire-pudding** [comment]
@BWPanda - I note the wiki is not there yet.  Please can you activate it.

**Comment by yorkshire-pudding** [comment]
Putting in here so doesn't get lost

`
### Shared Hosting

It may be possible to use Bee on your shared hosting if you have SSH access (or a virtual terminal - see Advanced > Terminal in your cPanel or equivalent) and if it will support aliases. See [this META issue](https://github.com/backdrop-contrib/bee/issues/154) for a list of shared hosts where this method has been tested and confirmed to work using the simple test above.

#### Manual (based on cPanel File Manager)
- Download zip from GitHub
  - Click on green 'Code' button
  - Click on 'Download ZIP'
- Upload zip to root of your home folder on your shared hosting account
- Extract zip to root of home folder
  - Select the uploaded zip file
  - Click on 'Extract'
  - Leave the path blank
  - Click on 'Extract File(s)'
- Rename folder to 'bee'
- Add alias
  - Open .bashrc to Edit
  - Add `alias bee='~/bee/bee.php'` to the bottom of the file
  - Click 'Save Changes'

You should now be able to complete the test by accessing your backdrop folder through SSH or your virtual terminal.

#### Using Git

- On your cPanel homepage, click on 'Git&#x2122; Version Control' under Files (if this isn't there in your cPanel, you won't be able to use this method and will need to use the manual method above)
- Click Create
- Ensure the switch for 'Clone a Repository' is switched on
- Copy the Clone URL from this Git repository (Code>Clone) and paste it into the 'Clone URL' field
- enter the folder name (i.e. 'bee') under 'Repository Path'
- enter a 'Repository Name; (e.g 'Bee' or 'Backdrop Bee' )
- Click 'Create'
- Add alias
  - Open .bashrc to Edit
  - Add `alias bee='~/bee/bee.php'` to the bottom of the file
  - Click 'Save Changes'

You should now be able to complete the test by accessing your backdrop folder through SSH or your virtual terminal.

You will be able to update your installation by clicking on 'Manage' and then 'Update'.
`

**Comment by ghost** [comment]
> @BWPanda - I note the wiki is not there yet. Please can you activate it.

Done.

**Comment by yorkshire-pudding** [comment]
Thanks - I've added the shared hosting installation to a page on the wiki.
