### ISSUE TITLE
Flushing the "CSS & JS" cache does not refresh the aggregated files

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#157]
When running `bee cc` and then selecting `2` (CSS & JS) no new CSS or JS files get created under /files/css or /files/js.

Same when running `bee cc all` - no fresh files, so the cache flush IMO doesn't work as expected.

```
Select a cache to clear:

 [0] All                          
  1  Core (page, admin bar, etc.) 
  2  CSS & JS                     
  3  Entity                       
  4  Layout                       
  5  Menu                         
  6  Module                       
  7  Theme                        
  8  Token                        
  9  Update                       

Enter a number: 2

 [✔] Cache(s) cleared: CSS &amp; JS 
```
But no new files.

Not sure, what's happening here, will try to dig deeper ASAP.

bee version: latest dev (git clone)

**Comment by indigoxela** [comment]
Ah, OK, bee is using function _backdrop_flush_css_js():

```
/**
 * Changes the dummy query string added to all CSS and JavaScript files.
 *
 * Changing the dummy query string appended to CSS and JavaScript files forces
 * all browsers to reload fresh files.
 */
function _backdrop_flush_css_js() {
  // The timestamp is converted to base 36 in order to make it more compact.
  state_set('css_js_query_string', base_convert(REQUEST_TIME, 10, 36));
}
```
But that function does _not_ regenerate or even flush anything, it just sets a new query string (on the old files in our case).

What I'd expect here is to also run:

```
  backdrop_clear_css_cache();
  backdrop_clear_js_cache();
```
Or am I missing something?

**Comment by indigoxela** [comment]
FTR drush is doing like I thought bee should: https://github.com/drush-ops/drush/blob/b0d4dca23ce7b6ece76797fae622f751c06c116d/commands/core/drupal/cache.inc#L80

@BWPanda I know how little time you currently have, so I assume that a PR is futile. I'll patch my local install and come back with a PR, when you feel like it's possible to work on bee again. :wink: 

EDIT: it's not that - something else is fishy here, so this cache doesn't get flushed. Giving up for now and doing it over UI.

**Comment by ghost** [comment]
> EDIT: it's not that - something else is fishy here, so this cache doesn't get flushed. Giving up for now and doing it over UI.

Interesting... Marking this as a question until we determine if it's a bug or not...

**Comment by ghost** [comment]
FTR, Bee does the same as Drush, and more:

https://github.com/backdrop-contrib/bee/blob/45bf76a60743ad8425d5bb3240aa6c0fdbe983a7/commands/cache.bee.inc#L70-L75

**Comment by indigoxela** [comment]
Maybe we should just close this issue? In the meantime I think, it works as designed.
