### ISSUE TITLE
Set user-login to default to #1 user when no username is provided

### ISSUE THREAD

**Issue by wilburec** [backdrop-contrib/b#158]
Current Behavoir:

When running `bee user-login`, the system responds with `Argument 'username' is required.`

Expected behavior:

When running `bee user-login`, the system defaults to the #1 user, and provides a user login.

**Comment by ghost** [comment]
Thanks for the suggestion @wilburec! Fixed in https://github.com/backdrop-contrib/bee/commit/5dbd5487dac0e451cdc35a876a041b9b689ded68.
