### ISSUE TITLE
UX: Add friendly messages in the site-install command

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/b#162]
Coming from drush-land, I was expecting the `site-install` command to run in unattended mode by default (see #160). It would help if before the prompts there was an info message along these lines:

`[i] Running installation in interactive mode. To run unattended, use the --auto switch.`

Also, the respective command in drush shows a friendly message when beginning the installation, to inform people that the script may take a while (with bee I though that it got stuck for a moment). How about bee doing the same in an info message?:

`[i] Installing Backdrop. This may take a moment...`

**Comment by ghost** [comment]
Thanks Greg. Fixed in https://github.com/backdrop-contrib/bee/commit/27c213df95e5f97a09453a18d5753f2c4a0c0ec6
