### ISSUE TITLE
Running site-install in --auto mode uses admin@example.com instead of provided username.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/b#167]
I've been using this in my scripts:

`lando bee si --profile=standard --db=mysql://root:backdrop@localhost/backdrop --username=admin --password=password --site-name=my-site --auto`

I think it was working as expected till recently, but I tried it today, and could not log into the instance. I then used `bee uli` to log into the site as user1, only to find out that the username was set to `admin@example.com`.

**Comment by ghost** [comment]
Oops: `$email = "--account-name=$email";` https://github.com/backdrop-contrib/bee/blob/82a634f2e9afdfc3df11d6e36fb7834b2e954081/commands/install.bee.inc#L136 😄

**Comment by ghost** [comment]
@klonos Can you please try the PR ^ ?

**Comment by klonos** [comment]
Thanks @BWPanda ...it works as expected now 👍🏼
