### ISSUE TITLE
Contrib folder

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/b#169]
If a `contrib` folder exists in the `modules` folder, perhaps `bee` should automatically use that when downloading contrib modules with the `bee dl` command.

**Comment by ghost** [comment]
It should already do that: https://github.com/backdrop-contrib/bee/blob/45bf76a60743ad8425d5bb3240aa6c0fdbe983a7/commands/download.bee.inc#L87

But looks like I made a typo 🤦‍♂️ Care to file a PR @laryn?

**Comment by laryn** [comment]
Thanks @BWPanda -- I've filed https://github.com/backdrop-contrib/bee/pull/170

**Comment by ghost** [comment]
Thanks @laryn! Merged.
