### ISSUE TITLE
PHP 5 compatibility fixes

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/b#171]
I tried to spin up a Backdrop instance with lando, with php 5.4 (I needed to test things with php < 5.6), and I got the following error repeated multiple times:

```
Parse error: syntax error, unexpected '=', expecting ')'
in /usr/local/bin/bee/includes/render.inc on line 87
```

I also got this:

```
Fatal error: Can't use method return value in write context
in /usr/local/bin/bee/commands/config.bee.inc on line 103
```

Then this:

```
Parse error: syntax error, unexpected '=', expecting ')'
in /usr/local/bin/bee/commands/download.bee.inc on line 245
```

Then this:

```
Parse error: syntax error, unexpected '=', expecting ')'
in /usr/local/bin/bee/commands/status.bee.inc on line 65
```

**Comment by klonos** [comment]
@BWPanda I've filed a PR here: https://github.com/backdrop-contrib/bee/pull/172

I'm using `bee si`, `bee en`, and `bee cset` on my local, so I've tested those commands only. Other code might also be incompatible with php versions < 5.6, but this should be a starting point.

**Comment by ghost** [comment]
I'm wondering about the benefits of adding support for early versions of PHP 5, especially when Backdrop's about to drop support for it...

**Comment by yorkshire-pudding** [comment]
@klonos - given that PHP 5.6 is now the minimum are you happy to close this ticket and the PR?

**Comment by klonos** [comment]
Yup. Fine by me 👍🏼
