### ISSUE TITLE
Looking for co-maintainer

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#173]
It is with much sadness that I admit I haven't put as much time and effort into Bee as it deserves. From what I hear in the community, there is a lot of interest in Bee, especially getting it closer in line with Drush and Brush feature-wise. Unfortunately though, I don't seem to have (or make) the time for it (it also probably doesn't help that I don't do much with Backdrop on the command line nowadays either).

So I'd like to bring a co-maintainer onboard. I'd like to stay as a maintainer myself, just so I can help guide the direction of the project and because I've put so much work in so far that I don't feel like letting it go fully yet. But I could definitely use some help! 🙂 

Any volunteers? Ideally the new co-maintainer will have been contributing to Bee already...

**Comment by yorkshire-pudding** [comment]
@BWPanda - I am possibly interested in this.  I think bee is already a great tool and would like it to be as rich a command line tool as people need.  I would appreciate some mentoring to help me get to grips with the different approaches used and particularly interfacing with backdrop core functions.

**Comment by ghost** [comment]
Sure @yorkshire-pudding! Make a PR adding your name to the README as a maintainer and I'll merge it (that's the official way). Happy to help you out with any questions, etc., just PM me in Zulip if you need help with anything.
