### ISSUE TITLE
Undefined index: version in projects command

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#177]
**Steps to reproduce**

1. Have one or more custom theme/module/layout installed
2. run 'bee projects' or 'lando bee projects'

**Expected result**
table runs with no errors - either blank or says "No version" in version column for these

**Actual result**
Table runs but with following error at top (this was for theme)

```
Undefined index: version
 /usr/local/bin/bee/commands/projects.bee.inc:165
```

**Comment by ghost** [comment]
Thanks @yorkshire-pudding ! PR merged.
