### ISSUE TITLE
Database functions fail if db_password contains special characters

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#181]
This also applies to db_name and db_username but these are less likely to have special characters.
For the purposes of Backdrop where `rawurlencode` is used, special means anything except `A-Z, a-z, 0-1, - _ . ~`
https://www.php.net/manual/en/function.rawurlencode.php

**Steps to reproduce**

1. Create a backdrop database
2. Set the users password to have special characters
3. Attempt `install`, `db-import`, `db-export`, `sql`,  or `status --show-password`

**Expected result** works as normal

**Actual results** 
`install`, `db-import`, `db-export`, `sql` will all fail
`status --show-password` will show the encoded password

The backdrop GUI installer `core/install.php`, powered by `core/includes/install.inc`, uses `rawurlencode()` for db_name, db_username and db_password so what is stored in `settings.php` has these values encoded. 

If the `rawurldecode()` function is not used to read the database information stored in `settings.php` then the value returned will be encoded and so won't match the actual DB password.

**Comment by ghost** [comment]
Left a review requesting changes.

**Comment by yorkshire-pudding** [comment]
@BWPanda - done all the `db.bee.inc` changes.
Might be worth a discussion about the `install.bee.inc` changes.  As [stated on the PR](https://github.com/backdrop-contrib/bee/pull/183#discussion_r848142235), I tried `parse_url` and it couldn't handle complex passwords.

**Comment by ghost** [comment]
Thanks so much for this @yorkshire-pudding! Did a final review, made one small change I didn't notice before, and merged!
