### ISSUE TITLE
Choose a testing framework and implement.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/b#19]
We need tests!

**Comment by ghost** [comment]
Thinking of using [PHPUnit](https://phpunit.de/) for the tests and [Travis CI](https://travis-ci.org/) for automatically running them on pull requests...

Also, to save users having to download the tests unnecessarily when simply using `b`, we could setup a `testing` branch that is a copy of the main branch (`1.x-1.x`) but with the tests and Travis integration included. Then testing could be performed against the `testing` branch with one of the setup steps being to merge in the `1.x-1.x` branch.

Thoughts?

**Comment by indigoxela** [comment]
Regarding the testing branch: I wouldn't mind to have the tests directory in the regular install. They don't do any harm. An extra branch might be more overhead than necessary.

**Comment by ghost** [comment]
Mmm, OK. Guess we can always move tests to a separate branch later if needed...

**Comment by ghost** [comment]
Tada! Tests: https://github.com/backdrop-contrib/b/pull/69

**Comment by ghost** [comment]
Just converted manual setup of PHPUnit and PHPCS to Composer at @serundeputy's suggestion.

Tests are passing, just need to address coding standards (in [another issue](https://github.com/backdrop-contrib/b/issues/73)).

**Comment by ghost** [comment]
Committed!
