### ISSUE TITLE
Document ability for modules to add custom commands

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/b#190]
Many contirb modules already provide drush commands. It would be fantastic if these commands would automatically work with bee as well, but if not, bee should allow these modules to provide bee commands also. 

Here is a partial list of backdrop contrib modules that currently include `modulename.drush.inc` files:

* https://github.com/backdrop-contrib/path_redirect_import/blob/1.x-1.x/path_redirect_import.drush.inc
* https://github.com/backdrop-contrib/devel/blob/1.x-1.x/devel_generate/devel_generate.drush.inc
* https://github.com/backdrop-contrib/devel/blob/1.x-1.x/devel.drush.inc
* https://github.com/backdrop-contrib/coder_review/blob/1.x-1.x/coder.drush.inc
* https://github.com/backdrop-contrib/coder_review/blob/1.x-1.x/coder_review.drush.inc
* https://github.com/backdrop-contrib/coder_review/blob/1.x-1.x/coder_sniffer/backdropcs.drush.inc
* https://github.com/backdrop-contrib/pirate/blob/1.x-1.x/pirate.drush.inc
* https://github.com/backdrop-contrib/multifield/blob/1.x-1.x/multifield.drush.inc
* https://github.com/backdrop-contrib/backup_migrate/blob/1.x-1.x/includes/backup_migrate.drush.inc
* https://github.com/backdrop-contrib/bakery/blob/1.x-1.x/bakery.drush.inc
* https://github.com/backdrop-contrib/ds/blob/1.x-1.x/drush/ds.drush.inc
* https://github.com/backdrop-contrib/auto_nodetitle/blob/1.x-1.x/auto_nodetitle.drush.inc
* https://github.com/backdrop-contrib/search_api/blob/1.x-1.x/search_api.drush.inc
* https://github.com/backdrop-contrib/linkchecker/blob/1.x-1.x/linkchecker.drush.inc
* https://github.com/backdrop-contrib/votingapi/blob/1.x-1.x/votingapi.drush.inc
* https://github.com/backdrop-contrib/colorbox/blob/1.x-1.x/drush/colorbox.drush.inc
* https://github.com/backdrop-contrib/webform_stripe/blob/1.x-1.x/webform_stripe.drush.inc
* https://github.com/backdrop-contrib/print/blob/1.x-1.x/includes/print.drush.inc
* https://github.com/backdrop-contrib/metatag/blob/1.x-1.x/metatag_importer/metatag_importer.drush.inc
* https://github.com/backdrop-contrib/feeds/blob/1.x-1.x/feeds.drush.inc
* https://github.com/backdrop-contrib/project/blob/1.x-1.x/project_release/project_release.drush.inc
* https://github.com/backdrop-contrib/boilerplate/blob/1.x-1.x/boilerplate.drush.inc
* https://github.com/backdrop-contrib/d3/blob/1.x-1.x/d3.drush.inc
* https://github.com/backdrop-contrib/nodequeue/blob/1.x-1.x/modules/nodequeue_generate/nodequeue_generate.drush.inc
* https://github.com/backdrop-contrib/radix/blob/1.x-1.x/radix.drush.inc
* https://github.com/backdrop-contrib/potx/blob/1.x-1.x/potx.drush.inc
* https://github.com/backdrop-contrib/select2/blob/1.x-1.x/blob/1.x-1.xdrush/select2.drush.inc
* https://github.com/backdrop-contrib/xmlsitemap/blob/1.x-1.x/blob/1.x-1.xxmlsitemap.drush.inc
* https://github.com/backdrop-contrib/geocoder/blob/1.x-1.x/geocoder.drush.inc
* https://github.com/backdrop-contrib/services/blob/1.x-1.x/services.drush.inc
* https://github.com/backdrop-contrib/webform/blob/1.x-1.x/webform.drush.inc
* https://github.com/backdrop-contrib/stripe/blob/1.x-1.x/stripe.drush.inc

**Comment by ghost** [comment]
This is already possible, please see: https://github.com/backdrop-contrib/bee/blob/1.x-1.x/API.md and https://github.com/backdrop-contrib/bee/blob/b51997b5caef40935c4a6cd1918143cacb7aa590/includes/command.inc#L187

All we need to do is better document this ability.

**Comment by ghost** [comment]
Readme and API files updated.
