### ISSUE TITLE
Add support for Drush's `php-script` command

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/b#191]
From today's discussion at Backdrop LIVE:

> @jromine: I use "drush php-script foo.php" frequently. Does Bee have that?

AFAICT It looks like this command is not yet supported, so creating an issue to discus it :)

**Comment by ghost** [comment]
I wonder, what is the use-case for this over just making `foo.php` executable and running that directly...?

**Comment by jromine** [comment]
> I wonder, what is the use-case for this over just making `foo.php` executable and running that directly...?

drush php-script runs a php script after a full bootstrap, with the Backdrop API available.
With this script named /tmp/a.php:
```
<?php
$u = user_load(1);
print_r($u);
```

php /tmp/a.php throws an error.
drush php-script /tmp/a.php prints out a user object, as expected.

**Comment by yorkshire-pudding** [comment]
@jenlampton @jromine - does `bee eval` work in this case?  `eval` works after bootstrapping Backdrop - [see wiki](https://github.com/backdrop-contrib/bee/wiki/Usage#eval)
Could you do `bee eval "include 'foo.php';"` ?  I tried and this is the result:

```bash
user@hostname:~/projects/bee/backdrop$ lando bee eval "include '../foo.php';"
User Object
(
    [uid] => 1
    [name] => admin
    [pass] => $S$EWNThPomBTL8Kkf1BXg99b0kRnjtfDh6C7DyKrHuVLaaS9akH2i9
    [mail] => admin@example.com
    [signature] =>
    [signature_format] =>
    [created] => 1664557200
    [access] => 0
    [login] => 1664557200
    [status] => 1
    [timezone] => UTC
    [langcode] => und
    [preferred_langcode] => und
    [picture] => 0
    [init] => admin@example.com
    [roles] => Array
        (
            [0] => authenticated
            [1] => administrator
        )

    [is_active_revision] => 1
    [language] =>
    [data] =>
    [path] => Array
        (
            [pid] => 3
            [source] => user/1
            [alias] => accounts/admin
            [langcode] => und
            [auto] => 1
        )

)
```
`foo.php` contained your php above

Looks like this does a similar function, albeit with this you can include inline php, and if you want a file, you need to use `include` or `require`.  If `php-script` is needed for familiarity, then it could probably be done by either wrapping around this function or replicating it with a small variation.

**Comment by yorkshire-pudding** [comment]
Reference:
Command definition: https://github.com/drush-ops/drush/blob/73ecb31e2e21f927eec81645ab610854644b126c/commands/core/core.drush.inc#L230-L252
Command code: https://github.com/drush-ops/drush/blob/73ecb31e2e21f927eec81645ab610854644b126c/commands/core/core.drush.inc#L1105-L1175

Replicating the full functionality of drush's `php-script` would be more complicated.
The use case given above, which could probably be done with a simple function is less involved.

**Comment by herbdool** [comment]
Looks manageable. The drush version accounts for a couple different ways of including the script and also passing parameters to it. https://www.drush.org/latest/commands/php_script/

The docs make a mention of making a drush command as preferable. I'm curious to know if that's possible with bee at this point.

**Comment by yorkshire-pudding** [comment]
Hi @herbdool there is an API to make custom commands documented in [the wiki ](https://github.com/backdrop-contrib/bee/wiki/Extending-Bee) and in [API.md](https://github.com/backdrop-contrib/bee/blob/1.x-1.x/API.md).

Also, if a new command is likely to be useful to lots of people, we can consider including it, either as an extension to an existing command or as a new command entirely.

I also think we have a viable workaround using `eval` and `require`/`include` as well as the API so I'm not minded myself to prioritise this request, but we're always open to pull requests from collaborators if having `php:script` (might need to be `php-script` to avoid reworking the command parser) is a must have.

**Comment by herbdool** [comment]
@yorkshire-pudding I've added a PR. And it has passing tests! I've kept it simpler than the drush variation since I feel it was overly complicated.

 A path and filename extension is required (unlike drush which allowed just a name). A relative path will always be relative to the Backdrop site webroot. And an absolute path will also work. There's no option to load all scripts from one directory.

**Comment by yorkshire-pudding** [comment]
Thanks @herbdool - this is great.  I've added a code review with a request to add it to the `php.bee.inc` file and tests rather than being separate files.

**Comment by yorkshire-pudding** [comment]
Thank you to @herbdool for a great first contribution to `bee`!
