### ISSUE TITLE
Get bee added to backdrop recipe for lando

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#192]
Further to the discussion at Backdrop Live, I've added a request in the lando/backdrop queue to add bee to the backdrop recipe:

https://github.com/lando/backdrop/issues/13

@quicksketch @keiserjb - would either of you consider raising similar tickets for DDEV?
@Wylbur - would you consider raising a similar ticket for docksal?

I don't use either of these and don't have the time or inclination to learn so would be better coming from someone who uses these tools.

**Comment by ghost** [comment]
@yorkshire-pudding Thanks for this! Perhaps consider making the first word ('Bee') in your Lando issue a link to https://github.com/backdrop-contrib/bee...

**Comment by quicksketch** [comment]
First step for me here was to figure out how to actually get `bee` working with DDEV. I figured out something that works based off the [Lando](https://github.com/backdrop-contrib/bee/wiki/Using-bee-with-Lando) documentation and made a new wiki page here: https://github.com/backdrop-contrib/bee/wiki/Using-bee-with-DDEV

**Comment by yorkshire-pudding** [comment]
Thanks for the Wiki write up @quicksketch

**Comment by yorkshire-pudding** [comment]
Completed in https://github.com/lando/backdrop/issues/13
