### ISSUE TITLE
config-set (cset) puts speech marks around true/false and numeric

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#194]
If I do:

```bash
bee config-set system.core theme_debug true
```

then what appears in `config/active/system.core.json` is 

```json
  "theme_debug": "true",
```
And the setting doesn't change.

If I enable it in the UI, then what appears is:

```json
    "theme_debug": true,
```

The same seems to be true for numeric values, though I note that some numeric values around images are stored in quotes, so not sure how to handle that.

**Comment by ghost** [comment]
Noting here for posterity what @yorkshire-pudding and I discussed during office hours:
- I believe this is simply the nature of issuing commands via a command line - everything that Bee receives is a string, there's no knowledge of booleans, numbers, etc.
- As such, not sure there's an easy solution for this
- Having said that, we should see if Drush has the same issue or if they've solved it somehow
- Possibly there's a way to make it so users can enter something like `bee config-set system.core theme_debug bool(true)` and then Bee parses that to send the appropriate type...
- A workaround might be to just use something like this instead: `bee eval "config_set('system.core', 'theme_debug', TRUE)"`

**Comment by yorkshire-pudding** [comment]
I don't think drush handles this ([see code](https://github.com/drush-ops/drush/blob/73ecb31e2e21f927eec81645ab610854644b126c/commands/core/config.drush.inc#L293-L353))

Will explore other options

**Comment by yorkshire-pudding** [comment]
I have done a similar approach to what I did in `state-set`; I check the type of the existing config and try to set it to be the same type.

Feedback and testing welcome.
