### ISSUE TITLE
Add a version command for version reporting.

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop-contrib/b#203]
As is the case with Drush, I am proposing that Bee should have a mechanism of reporting the current version number. I welcome thoughts?

**Comment by yorkshire-pudding** [comment]
@ElusiveMind - thanks for this idea and the PR.  I can see the value in this though we may need to ensure we do more regular releases once PRs are merged.  My one reservation with this PR is it requires a manual edit of `includes/globals.inc` each time.  @BWPanda - what do you think?  Is this the right place to store it? Is there a better way? Could it be added as part of packaging a release?

**Comment by ghost** [comment]
I think that's how Backdrop Core does it (it's set to `1.N.x-dev` by default, then updated to `1.N.0` for the release, then to `1.N+1.x-dev` afterwards):
- https://github.com/backdrop/backdrop/commit/f51618559e36bf814283a5343cad1127bd42dc95
- https://github.com/backdrop/backdrop/commit/e6aae124678820b45cce2a8cda7b9021491e2418
- https://github.com/backdrop/backdrop/commit/0cd444f45c00eef18bf4ca70ac49ddc38116d4e3

In Bee's case, I'd prefer it to just be `1.x-1.x` by default, and only changed before/after a new release.

**Comment by indigoxela** [comment]
Maybe I'm leaning out far here - but it seems like we have consensus.

@ElusiveMind just some small coding standard suggestions on your PR.

**Comment by yorkshire-pudding** [comment]
@indigoxela @ElusiveMind - yes - I agree that with @indigoxela 's suggested tweaks this should be merged.  Then we should start doing releases using the approach recommended by @BWPanda above.

If this is merged after #219 then perhaps we could also include the version (referring to the global that this adds) to the `bee status` command.

**Comment by yorkshire-pudding** [comment]
Thank you @ElusiveMind for this PR - it has now been merged.
