### ISSUE TITLE
[META] Add PHP 8.1 Support

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#210]
## Identify issues

- [x] #189 
- [x] #215 
- [x] #211 
- [x] #222
- [x] #213
- [x] #225 

## Notes
So far, php functions that have caused the passing null to type string have been various string function:
`mb_strlen()`, `explode()` 

Might be worth looking at others:
`substr()`, `strpos()`, `str_replace()`,  `preg_match()`, `strip_tags()`, `rawurldecode()`, `rawurlencode()`, `exec()`, `unserialize()`, `json_decode()`, `trim()`, `eval`

**Comment by indigoxela** [comment]
@yorkshire-pudding the first one is a duplicate of #189 (Uncaught ArgumentCountError: Too few arguments to function bee_error_handler()).

The second has been mentioned already in another issue (can't remember/find which one) and can get fixed easily by casting to string.

Yes, to run bee with php8.1 one needs a lot of patches :grin:

**Comment by yorkshire-pudding** [comment]
@indigoxela - I know about the first one - I just wanted to reference it here - you'll note I've also referenced the PRs to avoid any duplication of effort.
I'd started identifying the fix for the casting and seen that in other backdrop issues so can do that.

Are you aware of any other areas?

**Comment by indigoxela** [comment]
> I'd started identifying the fix for the casting and seen that in other backdrop issues so can do that.

There it was - just a comment: https://github.com/backdrop-contrib/bee/issues/205#issuecomment-1221273936

> Are you aware of any other areas?

I didn't dig much deeper, just switched back to php7.4.

**Comment by yorkshire-pudding** [comment]
A big thanks to @indigoxela who has helped to identify and resolve the issues preventing full compatibility with PHP 8.1.  As the last of the identified issues has been fixed and merged, this issue can be closed.
