### ISSUE TITLE
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated - bee cron

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#222]
When running `bee cron`, there are several deprecated messages, on PHP 8.1.

It's caused by the $_SERVER['SERVER_SOFTWARE'] being set to NULL in bee_initialize_server(), but that is evaluated as string in core/includes/bootstrap.inc

Another task in meta #210.

**Comment by indigoxela** [comment]
And here's the simple PR for that: #223

**Comment by yorkshire-pudding** [comment]
I can confirm that this fixes the `preg_match()` PHP 8.1 issue. 

<details>
<summary>Pre patch errors for reference</summary>

```
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
 /app/backdrop/core/includes/bootstrap.inc:806

preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
 /app/backdrop/core/includes/bootstrap.inc:819

preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
 /app/backdrop/core/includes/bootstrap.inc:832
```
</details>

This may be a separate issue, but I also get the following errors running `bee cron` on 8.1:

```
stat(): stat failed for /tmp/update-cache-e4020ea2
 /app/backdrop/core/includes/stream_wrappers.inc:841

stat(): stat failed for /tmp/update-extraction-e4020ea2
 /app/backdrop/core/includes/stream_wrappers.inc:841
```

Do you also see this on 8.1 or could this be a lando specific issue?

**Comment by indigoxela** [comment]
> Do you also see this on 8.1 or could this be a lando specific issue?

Yep, also see it. It's not Lando specific. But it's a core quirk, I guess (see [this issue](https://github.com/backdrop/backdrop-issues/issues/5840)).

Bee would suppress that error, btw, if you reduce error_reporting in your php.ini for cli.

Alternatively we could do something in bee_error_handler(). Not sure what to do, but it should be a different issue.

**Comment by yorkshire-pudding** [comment]
Thanks @indigoxela
