### ISSUE TITLE
PHP 8+ warning: stat failed for /tmp/update-cache-XXXX on cron runs

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#225]
This is a follow-up to #41 and part of the PHP compatibility meta #210.

In php8+ the `@` error operator handling has changed a bit - it will now enforce an error level > 0.

That means that the warnings are back - two for every cron run:

```
stat(): stat failed for /tmp/update-cache-92ff6b81
...core/includes/stream_wrappers.inc:841

stat(): stat failed for /tmp/update-extraction-92ff6b81
...core/includes/stream_wrappers.inc:841
```

See also this related core issue: https://github.com/backdrop/backdrop-issues/issues/5840

I think, we have to catch it in Bee.

**Comment by indigoxela** [comment]
This seems to do the trick: #226.
Maybe not the smartest or most elegant solution, but should fix the annoying "stat failed" for each and every cron run on php8+, when the directories don't exist (yet).

**Comment by yorkshire-pudding** [comment]
Thanks @indigoxela - I've tested:
- running `bee cron` on PHP 8.1 ✔️ 
- running `lando run-tests` on PHP 8.1 ✔️ 
- running `lando run-tests` on PHP 7.4 ✔️ 

This makes sense to address this particular annoyance that could put off users.
