### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#228]
TBC

Location - Wiki

### Version number
- update global variable to version number. Commit
- Release
- reset global variable to `1.x-1.x`. Commit

### Other
- if new commands or changes to existing commands, update wiki
- Update changelog
- prepare release notes

**Comment by ghost** [comment]
> Location - md file or wiki or both?

Wiki please. Don't think this needs to be a file in the repo.

**Comment by yorkshire-pudding** [comment]
Completed at https://github.com/backdrop-contrib/bee/wiki/Release-Process
