### ISSUE TITLE
Invite @jlfranklin as a maintainer.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/b#23]
Hello @jlfranklin 

Thanks for all your great ideas and work in the `b` issue queue!
Would like to be a maintainer for `b`, that way you don't have to be blocked by Gor and I and as you introduce these features you can merge yourself?

If you don't have time or are not interested that is fine, but if you are I'd be happy to add you in and have you aboard the `b` project!

Let us know.

thanks,
~Geoff

**Comment by jlfranklin** [comment]
I would love to help maintain `b`.  Thank you.

**Comment by serundeputy** [comment]
Great!  Added you to the maintainers list: https://github.com/backdrop-contrib/b/blob/1.x-1.x/README.md

and gave you commit access!

Welcome and thanks for the help!

~Geoff
