### ISSUE TITLE
Re-evaluate error_reporting and error display, especially with PHP 8

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#231]
Since PHP 8 the behavior of the Error Control Operator (`@`) has changed, which is why I see more and more irrelevant errors.

> Prior to PHP 8.0.0, the error_reporting() called inside the custom error handler always returned 0 if the error was suppressed by the @ operator. As of PHP 8.0.0, it returns the value E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR | E_PARSE.

Sounds harmless but... All operations that try to flush some stale files or do some cleanup on cron runs, that need to check if such a file exists, now tend to throw errors.

We fixed that partly (for one command) in https://github.com/backdrop-contrib/bee/blob/1.x-1.x/bee.php#L50, but that's not sufficient.
The reason is in core: https://github.com/backdrop/backdrop-issues/issues/5840

So, we know that every `@what_ever_function()` will set the error handler to display at least ... errors - like `stat() failed`.

Currently Bee completely relies on error_reporting() to decide if it should display the message or not. And that will never return `0` for any file operation on non-existent files that ends up in core function url_stat().

Another example that causes nagging: `bee cc all` when the Color module is on. Fixing these problems one by one seems too inefficient.

My suggestion is to re-evaluate how error_reporting is handled in bee_error_handler().

**Comment by yorkshire-pudding** [comment]
I'm open to ideas.  We have a request (#22) for a `--quiet` option (there is a PR that does the opposite), so it would make sense if we do re-evaluate to do this at the same time.

**Comment by indigoxela** [comment]
I have to admit, that I don't have a clear idea yet, how to deal with the "unsilenced" errors with bee an PHP 8+.
We don't want to suppress all errors, only those that are clearly just "noise caused by core".

So I'm not sure, if #22 could accomplish what we need.

**Comment by indigoxela** [comment]
After short brainstorming in today's Office Hours: what if we suppress all errors with url_stat? Would that silence too much?

Testing and feedback is welcome. See #236

**Comment by indigoxela** [comment]
How to test: on **PHP 8+** only (no problem with version prior to 8.0):

1. Make sure that the temporary update cache directories do not exist and run `bee cron`
2. Create color settings with a theme (with Color module support), switch the theme, and run `bee cc all`

**Comment by yorkshire-pudding** [comment]
Minor comment tweak suggested, but this works great for getting rid of the numerous `stat` error messages.

**Comment by indigoxela** [comment]
> this works great for getting rid of the numerous stat error messages.

I'm a little bit concerned that this does too much, but on the other hand ... what else could go wrong in url_stat() that we'd need for debugging in Bee.

**Comment by yorkshire-pudding** [comment]
I haven't seen these come up with other function errors so maybe it is just these functions. What would someone do with these errors anyway? It gives no action.

**Comment by hosef** [comment]
Do you know why we are getting stat errors? Should we be checking that files exist before trying to access them in order to get rid of errors?

**Comment by indigoxela** [comment]
> Do you know why we are getting stat errors?

@hosef Probably this core issue describes the "why": https://github.com/backdrop/backdrop-issues/issues/5840
