### ISSUE TITLE
Disabling modules doesn't disable dependencies

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/b#24]
I had Views Slideshow and Views Slideshow: Cycle installed.  Using `b` to disable Views Slideshow did not disable the Cycle plugin.

Disabling a module should also disable any modules that depend on it.

**Comment by jlfranklin** [comment]
The state of the module list after disabling Views Slideshow:

![screen shot 2017-01-20 at 10 29 34 am](https://cloud.githubusercontent.com/assets/17887377/22155005/cce8cfda-defb-11e6-9767-24d1de878477.png)

Clicking "Save Configuration" without selecting anything new attempts to re-enable Views Slideshow to satisfy the dependencies.  (This part is more or less "works as designed", except that the module list should never be in this state.)

![screen shot 2017-01-20 at 10 30 06 am](https://cloud.githubusercontent.com/assets/17887377/22155006/ccf0fb42-defb-11e6-8fc6-ecf85508552f.png)

**Comment by ghost** [comment]
This has been fixed in the recent re-write.
