### ISSUE TITLE
Regression: prompts in commands which require higher bootstrap levels are broken

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/b#244]
This affects, for example update-db and config-import.

When no updates are available, all seems OK, but if there are, it's no longer possible to run `bee updb` without setting `-y`.

The command just gets stuck without any output. When hitting the enter key, the pending updates are shown, with a "Would you like to apply all pending updates? (y/N):" message and at the same time the command exits.

Not sure, what's causing that, need to dig a little later.

**Comment by yorkshire-pudding** [comment]
I wonder if it's related to #234

**Comment by indigoxela** [comment]
> I wonder if it's related to #234

Yes, I think it's related. We should probably combine these issues.

The prompt getting stuck is a regression caused by #222.

However: setting it back to NULL brings back the php 8 nagging. Setting it to *any* string (empty or whatever) breaks the prompts. <s>Not sure why that happens, and I've no idea how to solve it.</s>

**Comment by yorkshire-pudding** [comment]
Thanks for your investigation on this.
I guess the tests never pick this up as they bypass the prompts.

I tried commenting out the line and seemed to work on config-import.  I also checked status as an obvious candidate and that was fine.  I'll need to run it through the tests in case it breaks anything else but maybe that this line just isn't needed?

**Comment by indigoxela** [comment]
> but maybe that this line just isn't needed?

Unfortunately that line *is* needed. Otherwise all the php nagging is back with `bee cron` (see issue #222).

**Comment by yorkshire-pudding** [comment]
What if we take `$_SERVER['SERVER_SOFTWARE'] = '';` out of `miscellaneous.inc` and put in `cron_bee_callback()` ? `cron` doesn't have a prompt.  Might be there are other functions that need it too.

**Comment by indigoxela** [comment]
Oh, almost forgot... the problem seems related to core's function backdrop_is_cli(). That doesn't help us here, though. :stuck_out_tongue_winking_eye:

**Comment by indigoxela** [comment]
> What if we take $_SERVER['SERVER_SOFTWARE'] = ''; out of miscellaneous.inc and put in cron_bee_callback() ?

Interesting... :thinking: We currently don't have a lot of commands with the combo prompt + required bootstrap level higher than BACKDROP_BOOTSTRAP_PAGE_HEADER. Didn't check that, though. But that might only defer the problem.

**Comment by yorkshire-pudding** [comment]
Would it be reasonable to expect core to change to:

```php
function backdrop_is_cli() {
  return (empty($_SERVER['SERVER_SOFTWARE']) && (php_sapi_name() == 'cli' || (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)));
}
```
?

I note that `core/scripts/install.sh` has `$_SERVER['SERVER_SOFTWARE'] = NULL;` so that is going to cause problems for anyone installing using that on PHP 8.1

Then all the bee functions work.

**Comment by yorkshire-pudding** [comment]
if `backdrop_is_cli` is for `bee` and `drush` && `drush` does not work fully with PHP 8.1 && PHP 7.4 is no longer officially supported
then this function should be modified to work with `bee` on PHP 8.1

That's my logic; I wonder if core committers will accept that?

**Comment by indigoxela** [comment]
> ... `empty($_SERVER['SERVER_SOFTWARE'])`

That would be cool, but I'm not too confident, that this will happen. What do you think @quicksketch?

And even if it happens, it'll take some time.

With a fresher mind I'll try to figure out a (hopefully robust) workaround.

**Comment by yorkshire-pudding** [comment]
Added https://github.com/backdrop/backdrop-issues/issues/5872

**Comment by yorkshire-pudding** [comment]
@indigoxela - I've reverted the initial settings to `NULL` and used `backdrop_override_server_variables()` to set it to `''`

I've done an initial test with `cron`, `config-import` and `cc` and seems to work.
Also, all the automated tests are passing on both 7.4 and 8.1

**Comment by indigoxela** [comment]
Wow, good job! I didn't know that there's a core function for that. :smiley: This works for me.

One thing baffles me and might be worth another pair of eyes: that function's doc block states "This function can be called by command line scripts before bootstrapping Backdrop..." - in fact, in our case it has to get called *after* bootstrapping. Is that expected behavior?

**Comment by yorkshire-pudding** [comment]
Looking at the code and looking at what calls it, I think it is pretty standalone (it's not called by any other core function except `install_begin_request` - that happens after bootstrap) so while the intention may have been for it to be used before bootstrap, there is nothing that stops it being changed later, though some could have more of an impact than others.  Ultimately, the best solution would be for https://github.com/backdrop/backdrop-issues/issues/5872 to be merged and then `''` would work for `backdrop_is_cli` and the `preg_*` functions.  However, I think we should, unless there are compelling reasons not to, implement this in the interim (perhaps with a placeholder ticket to revert it once `#5872` is merged and released).

PS - I only found that function when searching in `core/includes/bootstrap.inc` for  `SERVER_SOFTWARE` so I could see what other functions used it.
