### ISSUE TITLE
Handle arguments provided in quotes as a single argument

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop-contrib/b#246]
This is related to #208 in where the goal is to add --extra=" { mysqldump flags } " support to the database export. This fix is a general fix for the parsing of command line parameters.

By default, parameters are split by -- and then by =. This creates a problem with you have a command such as:

```bee db-export --extra="--column-statistics=0 --no-tablespaces"```

Instead of treating the --extra items as a single parameter, it is split by -- and then by the equals sign to divide it up into multiple parts which are not understood by Bee.

The proposed fix is to modify `bee_parse_input()` to respect quoted arguments and then properly parse any possible equal signs within those commands in a way to be backward compatible to all existing Bee commands.

Referenced in pull request #247

**Comment by yorkshire-pudding** [comment]
@ElusiveMind - it looks like this is breaking the global option function and that is why tests are failing.

**Comment by yorkshire-pudding** [comment]
I might have an alternative approach.  Need to test some more.

**Comment by ElusiveMind** [comment]
Sounds good. I can look again later today if desired. I will be traveling Tuesday - Thursday. Just FYI.

**Comment by yorkshire-pudding** [comment]
@ElusiveMind - see [PR#249](https://github.com/backdrop-contrib/bee/pull/249)

After looking a bit at your code, and the original, I put in some temporary messages to check what was going on where and came up with an alternative approach that takes the whole value from the right of the equals sign; previously, the matching function had stripped out anything after the first space, and also where the value included an equals sign, that was also acting to split it up.  I've tested this with #248 and #208 and it seems to work; it also passes all the automated tests.
