### ISSUE TITLE
log command does not accept option with spaces

### ISSUE THREAD

**Issue by kbahey** [backdrop-contrib/b#248]
When trying to view dblog messages that are of a type that includes spaces (e.g. "page not found" or "access denied"), bee will not return any of them. 

The reason is that only the first word (e.g. "page" or "access") are passed as options to the callback. 

To test this out, try this:

```
bee.php --type='page not found'
or
bee.php --type='access denied'
```

**Comment by yorkshire-pudding** [comment]
Hi @kbahey - thank you for reporting this.
There is an enhancement that may resolve this at #246 
Needs some testing but I'll update here if that looks promising.

**Comment by yorkshire-pudding** [comment]
Hi @kbahey - there is a pull request at #249 that should fix your issue.  If you're happy testing PRs, please try applying the patch to your copy of `bee` and let me know.
