### ISSUE TITLE
Fix PHPCS Backdrop Standard violations

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#251]
As mentioned in #145, all the existing violations need to be addressed before we can consider integrating PHPCS checks.

**Comment by yorkshire-pudding** [comment]
- [x] Automated fixes
- [x] Ignore for `eval`
- [x] array hints for function declarations
- [x] replace old CS notations
- [x] function comments for test functions

**Comment by indigoxela** [comment]
@yorkshire-pudding is can see, you already started work. Let me know if you need any help. :relaxed:

**Comment by yorkshire-pudding** [comment]
Thanks for the offer @indigoxela - you'll see I've tagged you for review.

While most changes are fairly standard, I would appreciate your input on the class comments in the testing files - I've added a comment for ignore for eval.  There was an existing ignore with comment in `miscellaneous.inc` - I've now removed as it wasn't throwing up any warnings or errors with the current standard.

Tested with standard tests on upload with 7.4 and tested on local with 8.1 - all passed.

**Comment by indigoxela** [comment]
@yorkshire-pudding many thanks for your work. This all looks good to me.

Something catched my eye - but it's unrelated to phpcs: there are multiple usages of something like `$value = (bool) TRUE;`... Actually I don't think, type casting makes sense when it's already clearly the correct type, not a variable.

**Comment by yorkshire-pudding** [comment]
Thanks @indigoxela 
I'll merge this.  I'll have a look at those; I might have gone too far when trying to fix things that were going in with the wrong type.
