### ISSUE TITLE
b blows memory limits on hosts where memory_limit is not unlimited.

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/b#26]
On DreamHost, running `b --root $HOME/example.tld cron` blows up with `Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/myaccount/bin/backdrop_console/includes/render.inc on line 285`

Actual line number will vary by install.

**Comment by jlfranklin** [comment]
Turns out this is because b calls `exec('tput cols')`.  When running via cron, `$TERM` may not be set, returning `0` and an error on `STDERR`.  The rest of the code can't handle a terminal with width 0, and eventually overflows memory.

**Comment by ghost** [comment]
Looks good to me, thanks @jlfranklin!
