### ISSUE TITLE
Add the ability to execute SQL queries like drush sql-query command

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/b#265]
It would be very useful to be able to execute db queries as in `drush sql-query "SELECT title FROM {node}..."`.

Drush help is:

```
drush help sqlq
Execute a query against a database.

Examples:
 drush sql-query "SELECT * FROM users      Browse user record. Table prefixes, if used, must be added to table names by hand.               
 WHERE uid=1"                                                                                                                               
 drush sql-query --db-prefix "SELECT *     Browse user record. Table prefixes are honored.  Caution: curly-braces will be stripped from all 
 FROM {users} WHERE uid=1"                 portions of the query.                                                                           
 `drush sql-connect` < example.sql         Import sql statements from a file into the current database.                                     
 drush sql-query --file=example.sql        Alternate way to import sql statements from a file.

Arguments:
 query                                     An SQL query. Ignored if 'file' is provided.

Options:
 --database=<key>                          The DB connection key if using multiple connections in settings.php.  
 --db-prefix                               Enable replacement of braces in your query.                           
 --db-url=<mysql://root:pass@127.0.0.1/db  A Drupal 6 style database URL.                                        
 >                                                                                                               
 --extra=<--skip-column-names>             Add custom options to the database connection command.                
 --file                                    Path to a file containing the SQL to be run. Gzip files are accepted. 
 --result-file=</path/to/file>             Save to a file. The file should be relative to Drupal root. Optional.

Aliases: sqlq, sql:query
```

I'll work on this.

**Comment by yorkshire-pudding** [comment]
Sounds like it could be a useful addition.  Are there any particular use cases that this would be used for as its not something I've ever used in drush?

**Comment by bugfolder** [comment]
The place I use it is in my configuration script for my local site after mirroring it from production: I change various settings for testing in CiviCRM (using test gateways for financial processing, turning off scheduled jobs, etc.), by tweaking the db directly.

And there's a pending task on b.org right now, which requires direct db-tweaking (re-starting some security mailings). One can, of course, open mysql directly and issue db commands on the command line, but doing it via drush/bee means you can avoid having to enter mysql user credentials.

**Comment by yorkshire-pudding** [comment]
Thanks for the use cases @bugfolder - this makes sense.

**Comment by yorkshire-pudding** [comment]
Hi @bugfolder - how is progress on this?

**Comment by bugfolder** [comment]
Ummm...I think about it occasionally?

Consider me pinged 😉

**Comment by yorkshire-pudding** [comment]
@bugfolder 
My attention was brought to this issue and I spotted [this comment](https://github.com/backdrop-contrib/bee/issues/129#issuecomment-965724010):

> Just tested with `lando bee sql < backdrop-ready.sql` and it worked flawlessly. 👍  

I just did a test with a simple SQL script:
../test.sql
```sql
SELECT * FROM users;
```

then ran

```bash
lando bee sql < ../test.sql
```
and it worked.

```bash
 lando bee sql "SELECT * FROM users;"
```

didn't work, but I wonder how much use that would get anyway.  If you still want the full command then you are welcome to keep this open and deliver when you can, but if this will work for your use case, we can tweak the examples that currently say:

> Examples:
>  bee sql
>  Open a command-line for the current database.
> 
>  bee sql < backup.sql
>  Import an SQL file into the current database.

And close this.

**Comment by yorkshire-pudding** [comment]
@bugfolder - ping ^^

**Comment by bugfolder** [comment]
Ping noted.

**Comment by bugfolder** [comment]
As I was looking into this, porting all the stuff from the drush command was looking pretty complicated, and it seemed like overkill for what I really needed: just the ability to pass a db query to `db_query()`. So I implemented just that. But then since the functionality was now different from `drush sql-query`, I figured it shouldn't have the same name as the drush command. So I've called the command `db-query` (with alias `dbq`), and implemented it in the PR just filed.

**Comment by yorkshire-pudding** [comment]
Thanks @bugfolder - I've added some comments to the PR.

**Comment by bugfolder** [comment]
> I think this still fills a useful niche. I've made a few suggested changes below.

Changes made.

> In addition, it would benefit from a test in tests/backdrop/DBCommandsTest.php

I've added a stub of a test, but am wondering how to run the tests locally so that I can flesh it out further and test the tests.

**Comment by yorkshire-pudding** [comment]
> I've added a stub of a test, but am wondering how to run the tests locally so that I can flesh it out further and test the tests.

I run tests using lando. I'm not sure but @indigoxela might have setup to run local tests without lando.

**Comment by bugfolder** [comment]
Got testing set up. A test is added. (I think only one is needed; we don't need to try different individual queries, just verify that a given query is getting through.)

**Comment by indigoxela** [comment]
> I'm not sure but @indigoxela might have setup to run local tests without lando.

No, I'm not using Lando, either, so there's no way for me to run tests locally. The paths are hardcoded in tests to begin with "/app/", which won't work outside Lando. :shrug:
