### ISSUE TITLE
db-export command shows the wrong location if absolute path is used

### ISSUE THREAD

**Issue by TheMetMan** [backdrop-contrib/b#266]
Upon successful completion of the db-export command, the comment at line 144 prepends the Backdrop Root to the $filename for some reason, so the resulting comment looks as if the saved database is in a folder off the Backdrop Root which it is not.
So I think that line 114 should read as follows:
`'!filename' => $filename,`

**Comment by yorkshire-pudding** [comment]
Hmm. I'm not sure this is a bug. @TheMetMan - please provide an example of what the problem is.

If I run from my project root which is above the backdrop root (I have an alias setup that uses the `--root=docroot` argument)
```bash
$ lando bee db-export ../db-export.sql

 [✔] The 'backdrop' database was exported to '/app/docroot/../db-export.sql.gz'.
```
This, although long is an accurate path

Now `bee` always works from the backdrop root when deciding where to save the db export so in this scenario, with your suggested change, it would give a misleading response; it would say:
```bash

 [✔] The 'backdrop' database was exported to '../db-export.sql.gz'.
```
Which is incorrect from where I ran the command.

Possibly, if you always run from the backdrop root, then this change might make sense, but as it can be run from other places I'm not yet convinced that there is a bug.  If you could provide some more examples of how you use it in relation to the backdrop root, it would help to clarify if there is a case where this gives inaccurate paths.

**Comment by TheMetMan** [comment]
I am not saying this is a Bug as such, @yorkshire-pudding.
Here is what happens when I save to a folder outside the Backdrop Root, which is where I keep all my backups.
The resulting comment is not true.
`Saving Database and Settings to /home/francis/Backups/moduledevbd.scorpio/2023-03-04_15-39-32

 [✔] The 'moduledevbd' database was exported to '/home/francis/FG-Docs/public_html/moduledevbd.scorpio/web//home/francis/Backups/moduledevbd.scorpio/2023-03-04_15-39-32/database.sql.gz'. 

Finished
`

**Comment by yorkshire-pudding** [comment]
Right. It looks like you've got a script calling that.  Please can you give the line that is calling `bee db-export`?

I run Lando locally, so can't test with an absolute ref on that, but I've tested on my host and running from inside the docroot I can reproduce the error. I think it may need a slightly different approach to cover both scenarios (absolute path and relative path).

**Comment by TheMetMan** [comment]
The script is called like this (where moduledevbd.scorpio is the name of the site):
`./backupEssentials moduledevbd.scorpio`
Here is the relevant part of the script:

```
dateStamp=`eval date +%Y-%m-%d_%H-%M-%S`
DIRECTORY=~/Backups/$1/$dateStamp
bee db-export "${DIRECTORY}/database.sql"

```

and the database ends up here:

`'/home/francis/FG-Docs/public_html/moduledevbd.scorpio/web//home/francis/Backups/moduledevbd.scorpio/2023-03-04_15-39-32/database.sql.gz'`

**Comment by yorkshire-pudding** [comment]
Sorry, are you saying it saves to the wrong location? I thought it was just the message that was incorrect.  In my test on my host, it did save in the right location.

**Comment by TheMetMan** [comment]
No, @yorkshire-pudding, It is saved in the correct location. The message says it is saved in a folder off the Backdrop Root, which it is not.
It is the message which is incorrect

**Comment by yorkshire-pudding** [comment]
Got you.  When you said this, it suggested that the database export goes to the wrong place.

> and the database ends up here:
> 
>
>`'/home/francis/FG-Docs/public_html/moduledevbd.scorpio/web//home/francis/Backups/moduledevbd.scorpio/2023-03-04_15-39-32/database.sql.gz'`

**Comment by TheMetMan** [comment]
Sorry if I was unclear. No that is NOT where it ends up, that is where it Says it does. It ended up here:
`/home/francis/Backups/moduledevbd.scorpio/2023-03-04_15-39-32/database.sql.gz'`

**Comment by yorkshire-pudding** [comment]
@TheMetMan - I've created a [PR ](https://github.com/backdrop-contrib/bee/pull/267) and tested against both absolute and relative paths and it seems to work. Please will you test.
