### ISSUE TITLE
Does 'b.php' need to be executable?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#27]
The README says: "Make `b.php` executable". I forgot this step and started using it, and it worked fine. So is this step actually necessary?

I ask because I'd like to contribute to this project, but changing the file permissions of `b.php` makes it show up in git as a change which I have to remember not to commit... :slightly_smiling_face: 

Or, is it possible to make it executable and then commit that to the repo, then it's one less step for people to do themselves, right?

**Comment by indigoxela** [comment]
Actually it's not necessary.

This would only be the case, if b.php used a shebang  `#!/usr/bin/php` (which it doesn't)

Then the _php_  before _/path/to/..._ wouldn't be necessary, as a shebang already provides the path to your php executable.
Yet it would be necessary to write the full path to your b.php then, in case it's _outside_ your "$PATH".

If using a shebang _and_ making it executable _and_ it's inside $PATH, a simple `b.php` would execute.

Using an alias in one's profile is probably the most compatible solution.

**Comment by ghost** [comment]
Thanks @indigoxela, in that case I'll change this to a request to remove that step from the README.

**Comment by ghost** [comment]
Here's a [PR](https://github.com/backdrop-contrib/b/pull/32)

**Comment by indigoxela** [comment]
Another thing comes to my mind: depending on the hosting environment (provider) it might be necessary to provide the full path to the php executable. For instance, if several php versions are available in a chrooted environment.
