### ISSUE TITLE
Add the ability to handle multisites where the site folders are accessed via a symlink

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#270]
As discussed with @hosef there is a scenario where the Backdrop code base is within one directory path. For example:
```bash
/var/www/backdrop/1.24.x
```
and the sites folder are elsewhere and accessed via a symlink from the backdrop sites folder.

It may be possible to accommodate this with some small changes to the code.

**Comment by yorkshire-pudding** [comment]
@hosef  - got it mostly working using site folders within a different directory. Where it falls down is finding the site by the current location (i.e. when you are in folder of site - in lando `/app/multisite/sites/multi_two`); the issue it encounters is that once you're in that folder it can't find the root (unless you specify it).  It therefore is not going to pass the tests on a setup like this but I don't think it has to as tests will follow the standard pattern.  With these changes, it doesn't affect normal operation.
There is a PR attached for you to test.

>Can you confirm, is the sites.php down the symlink or is that within the backdrop folder (i.e. 1.24.x/sites/sites.php)?
I've worked on the assumption that the backdrop folder contains `sites` folder which contains `sites.php` file and then symlinks to each site folder. If this is not correct, it may still be possible  but might need some more work.

Let me know how you get on.

**Comment by hosef** [comment]
I tested the PR, and everything seems to still be working with the changes.
I determined that this was not the issue in my case, but these changes will probably still help with other cases so I think it would be a good idea to apply them.
