### ISSUE TITLE
Add command to enable and disable theme_debug setting

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#277]
As a site architect theming my site or a theme builder
I want to be able to enable and disable the `theme_debug` setting without the `devel` module
So that I can find the template I need to override without having to use a long `config-set` command or having to have `devel` enabled.

**Comment by bugfolder** [comment]
This issue caught my eye as an easy one to implement. 

Before I add the automated tests, let me ask about file/function organization. I put these two theme-related commands into new `theme.bee.inc`, but I see that the two existing theme-related commands are in `projects.bee.inc`. Do you want me to move these functions into that file, or move the two existing theme bee commands into this theme-dedicated command file?

**Comment by yorkshire-pudding** [comment]
Thanks @bugfolder
I think moving into `theme.bee.inc` would make sense.

The `group` they are in is `themes` which influence where they appear in the help text which strengthens the case for moving:

```
 THEMES
  theme-admin
   admin-theme
   Set the admin theme.

  theme-default
   default-theme
   Set the default theme.
```

**Comment by yorkshire-pudding** [comment]
@bugfolder - as an aside, commands can now be added to the wiki via the `docs` folder so you can include changes to the wiki as part of your pull request.

**Comment by bugfolder** [comment]
Tests added (and passing).

I'm not actually seeing a `docs` folder in the repo (nor any text from the wiki), so that is presumably in a separate repo?

**Comment by yorkshire-pudding** [comment]
You might need to rebase your branch to see it as it was added last night (UK time)

**Comment by bugfolder** [comment]
Yup, I rebased yesterday, but just did it again and see 70 new commits (my, you've busy!).

**Comment by yorkshire-pudding** [comment]
> Yup, I rebased yesterday, but just did it again and see 70 new commits (my, you've busy!).

Not quite. I wanted to keep the git history of the wiki so it didn't all appear as me (though a lot is) so I merged all the commits rather than doing a squash commit.

**Comment by stpaultim** [comment]
Just want to confirm that this is still being worked on and is not yet committed to Bee. Is that correct?

**Comment by yorkshire-pudding** [comment]
> Just want to confirm that this is still being worked on and is not yet committed to Bee. Is that correct?

Correct.  I'm wanting to do it similar to how I've done the maintenance mode command.

**Comment by yorkshire-pudding** [comment]
I've added a PR for theme debug command based heavily on the maintenance mode command. This made it very quick to develop with the main differences being terminology command and `state` vs `config`.

If anyone (i.e. @stpaultim @bugfolder ) would like to review and/or test you are welcome to do so. If not I will merge

**Comment by stpaultim** [comment]
I did finally test this, after it was released. It's working perfectly! Thanks.
