### ISSUE TITLE
Error on Wiki

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/b#278]
Just creating a ticket to show my work, so someone can correct me if I'm making a mistake here. 

I couldn't get the db-password to work here. @BWPanda let me know it should be db-pass instead. 

WAS:

![image](https://user-images.githubusercontent.com/3144571/229272047-e4c286e5-afa8-4b2f-90e9-fbc002ae233a.png)

I CHANGED IT TO:

![image](https://user-images.githubusercontent.com/3144571/229272120-ea0a113b-d034-444b-962b-24b554070c24.png)

Just want someone to verify this is correct. If so, you can close this issue.

**Comment by ghost** [comment]
Yes, that was a typo. Thanks for finding and fixing this @stpaultim!

**Comment by ghost** [comment]
FTR, this was an error in the actual command examples too a while ago, but fixed in July 2022: https://github.com/backdrop-contrib/bee/pull/193
