### ISSUE TITLE
Add mitigation(s) for Github API limit

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#304]
In the `download` command we use the api to get `.info` files.

Normally, this is not a problem, but if there are a lot of downloads from the same IP address then the download function can currently fail without giving the user particularly helpful feedback.

```
Illegal string offset 'type'
 /app/commands/download.bee.inc:326

Illegal string offset 'type'
 /app/commands/download.bee.inc:326

 [✘] The 'type' of project 'paragraphs_jquery_ui_accordion2' could not be determined.
```

I've encountered this before (when I was improving and testing the download command) but only today realised why I was getting it.

The API rate limit is 60/hour for anonymous users but 5000/hour if used with a Github Personal Access Token (classic) and 15,000/hour for Enterprises Users.

As a simple fix I can add a check in to the api `rate_limit` method (which doesn't use any quota) and provide a more meaningful error message including the time when they could retry.

However, if we assume that `bee` could be useful for agencies where you could have many developers updating multiple sites from one IP address, then it would be good to allow tokens to be used and for an error message to point this out.  I've tested a few different ways to include the token, but this is an area where it would be good to get some feedback.

Possible options are:
- a global or command level option added to the command (e.g. `--token=githubpersonalaccesstoken` (at present only `download` uses this, but others in the pipeline might); this could be rather cumbersome to use and also would expose the token to the command history.
- look for a particularly named text file in key places
- introduce the concept of `bee_settings` where we allow certain settings to be stored.  #131 will require some config storage for the alias definitions and  #110 mentions the possibility of settings to switch color off.  

Thoughts?

**Comment by laryn** [comment]
Ah, I think I just ran into this! It's a fatal error in PHP 8.1.

> PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /usr/local/bin/bee/commands/download.bee.inc:349

It was working fine and then suddenly wasn't. I tried rebooting, restarting my local environment, etc. but now I see...

I am not sure what to suggest yet but I'll try to think about it a bit. But catching this and providing more meaningful notes would be an important first step.

**Comment by laryn** [comment]
How does the project installer get around this? Is it just going straight to download without using the API, and then opening and getting the `.info` file after downloading? (e.g. I just added a big list of module names in the manual installation text box, and it works fine although `bee` is still throwing the error above)

**Comment by yorkshire-pudding** [comment]
@laryn  - I haven't looked at how the project installer does this. Perhaps it gets all the information from `b.org` ? In theory `bee` could do the same but I believe `projects.b.org` only allows actual Backdrop sites to interface with it's API.
I don't think it will be difficult to add a check and a message in.
I am planning to put the options file in so a personal access token could be stored but haven't got round to it yet.

**Comment by indigoxela** [comment]
So far I didn't run into this problem, yet. But we should really add at least a meaningful message, when this happens.

At which step does this happen?

**Comment by yorkshire-pudding** [comment]
@indigoxela it is when we call the API to find and get the info file. I'm working on a PR

**Comment by yorkshire-pudding** [comment]
@laryn @indigoxela 

I have prepared a PR. It includes some better error handling and checking of quota and meaningful messages.  There are also some debug logs around the quota checking so if you add `--debug` or `-d` you will get a summary of quota information every check.

It can be tested by repeatedly downloading a module with a few dependencies and then clearing the contents of the modules folder. I used `paragraphs_jquery_ui_accordion2` which depends on `paragraphs` which depends on `entity_plus`; gets to the limit quite quickly.

To test the GitHub Token, you will need a GitHub Personal Access Token (Classic)

I'm sure the wording can probably be improved; I've been looking at it too long!

**Comment by yorkshire-pudding** [comment]
@laryn @indigoxela - would you be willing to test and/or review?

**Comment by indigoxela** [comment]
@yorkshire-pudding sorry, I wouldn't even know, how to test. Unfortunately I never used GH tokens, so can't help with reviewing, either.

**Comment by laryn** [comment]
@yorkshire-pudding I will try to test, but this week is quite busy so I'm not sure if it will be before next.

**Comment by yorkshire-pudding** [comment]
I've done a few tweaks to the code, tested again. As this PR fixes a fatal error that confuses users, I am going to merge this now rather than wait until someone has time to test/review. Any bugs or enhancements to it can be raised separately.
