### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/b#305]
This is what I've seen using bee briefly under PHP 8.2 (using with Lando).

`bee uli`

> Using ${var} in strings is deprecated, use {$var} instead
 /usr/local/bin/bee-1.x-1.x/commands/download.bee.inc:76
> Using ${var} in strings is deprecated, use {$var} instead
 /usr/local/bin/bee-1.x-1.x/commands/download.bee.inc:449
> Using ${var} in strings is deprecated, use {$var} instead
 /usr/local/bin/bee-1.x-1.x/commands/download.bee.inc:452
> Using ${var} in strings is deprecated, use {$var} instead
 /usr/local/bin/bee-1.x-1.x/commands/download.bee.inc:455

I've tried a few other commands and this is the only warning I've seen so far.

**Comment by herbdool** [comment]
I've added a PR https://github.com/backdrop-contrib/bee/pull/306

**Comment by yorkshire-pudding** [comment]
Thanks. I'm checking now. Don't worry about the failing tests; we have an issue for that #287 but I will test locally

**Comment by yorkshire-pudding** [comment]
Thanks @herbdool - the tests all pass and it fixes the issue.
