### ISSUE TITLE
Addition of user commands

### ISSUE THREAD

**Issue by nico8948** [backdrop-contrib/b#313]
I don't how to comment the project, but i've added some user commands, like in brush.
i needed these options myself..

see my fork
https://github.com/nico8948/bee

i don't know if it's usefull

Commands:

- user-create
- user-cancel
- user-block
- user-unblock
- user-add-role
- user-remove-role

**Comment by yorkshire-pudding** [comment]
Hi @nico8948 
This is a great first contribution to the bee project. Thank you
If you:

1. Go to your fork
2. Click on the link where it says "This branch is 1 commit ahead of backdrop-contrib:1.x-1.x"
3. You should have a button that says "Create pull request"; click on that
4. Start the description of your pull request with `Fixes #313` which will link the PR to this issue.

![chrome_PLLgHV90fI](https://github.com/backdrop-contrib/bee/assets/20357797/b5ffcb4e-cb61-402f-b183-f3b1c58bcd6a)

Once submitted, I will set the tests to run; this is only needed until your first PR is merged.

There will likely be a few changes needed to meet coding standards, but I will provide suggestions and walk you through it.
Thanks again

**Comment by yorkshire-pudding** [comment]
Hi @nico8948 - thanks for your patience with this.

I've committed all the minor typos, wording improvements and phpcs corrections.  What is left is:

- removing the code that adds a role if it doesn't match - see [my comment here](https://github.com/backdrop-contrib/bee/pull/316#discussion_r1278313922)
- Adding tests.  Please let me know if you would prefer if I added these or whether you are happy to have a go.

**Comment by nico8948** [comment]
no problem, you are the owner. i'll look into the project on monday further. i'm busy now with house, family and other interests..

**Comment by yorkshire-pudding** [comment]
@nico8948 🎉  - great work in getting to a state with all tests passing. I'm going to download this version, give it a thorough review and test, and hopefully we can get this merged
