### ISSUE TITLE
PHPCS test is using an old tag

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#320]
I noticed that the phpcs workflow test was not picking up some issues that I am seeing locally with the latest version of the Backdrop phpcs standard. I tracked this down to the fact that is uses a tag `1.0.0.-beta1` from 2022. There are no newer tags.

It probably makes sense to just use the `main` branch so we don't need to keep track.

**Comment by yorkshire-pudding** [comment]
Fixed with commit 61010bc2319351158e1247bed373f22f2b15f7b3

**Comment by indigoxela** [comment]
How about asking to create a new tag? :wink:

Using tags has the advantage, that you always have a defined version in use. Otherwise things might change over night, and you don't know what happened.

**Comment by yorkshire-pudding** [comment]
That is an option, but I checked and saw there was just one tag over a year ago, so I didn't think they were being actively used.
Perhaps a question for the phpcs repo but how do you feel about creating new tags after a merge?

**Comment by indigoxela** [comment]
> Perhaps a question for the phpcs repo but how do you feel about creating new tags after a merge?

That might make sense. :thinking:
Actually, your contribution was the first one easy to merge. A new tag exists now, BTW. :wink:

**Comment by yorkshire-pudding** [comment]
> A new tag exists now, BTW.

Thanks - updated with that tag - 843f9f2804b8c8f651cf52efa405f4ed48e84ab9
