### ISSUE TITLE
Add node, menu, roles and permissions commands

### ISSUE THREAD

**Issue by nico8948** [backdrop-contrib/b#321]
Hi All,

In my fork (https://github.com/nico8948/bee) i've added  the files  node.bee.inc and role.bee.inc:

NODE                                                                                                                      
  menu-delete                               Delete a menu link.                                                            
  md                                                                                                                       
  
  menu-update                               Update or create a menu link.                                                  
  mu                                                                                                                       
  
  menus                                     List all menus.                                                                
  menu-list                                                                                                                
  
  node-delete                               Delete a node.                                                                 
  ndel                                                                                                                     
  
  node-update                               Add or update a node.                                                          
  nu                                                                                                                       
  
  nodes                                     List all nodes.                                                                
  nls, node-list               

                              ROLES                                                                                                                     
  permissions                               List all permissons of the modules.                                            
  pls, permissions-list                                                                                                    
  
  role-add-perm                             Grant specified permission(s) to a role.                                       
  rap                                                                                                                      
  
  role-create                               Add a role.                                                                    
  rcrt                                                                                                                     
  
  role-delete                               Delete a role.                                                                 
  rdel                                                                                                                     
  
  role-remove-perm                          Remove specified permission(s) from a role.                                    
  rrp                                                                                                                      
  
  roles                                     List all roles with the permissions.                                           
  rls, roles-list

**Comment by yorkshire-pudding** [comment]
@nico8948 - thank you for this. I don't have time to look in detail at these at the moment, but my first instinct is:

- node and menu commands - these are not really suitable for bee. I can't see there being wide usage (it is not in drush 8), it would be very difficult to support when people have issues and there are all sort of other modules that interact with nodes and menus that could cause problems. You can easily stick this in your own custom .bee folder - see https://github.com/backdrop-contrib/bee/wiki/Extending-Bee
- roles and permission - I would like to look at this further as I believe it has potential and could be useful in bee.

I won't be able to get to looking at it for a few weeks, but in the meantime you could look at a pull request for just that element and consider tests too.

**Comment by yorkshire-pudding** [comment]
Thank you for this valuable addition to bee @nico8948 . There will be a release shortly, but I have a few other things I'm working on that I want to merge in before I do that.
