### ISSUE TITLE
Allow the destination path to be included with the filename for sql-dump

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/b#325]
Right now the only place that database dumps can go is in the webroot of the site. This isn't ideal since it's exposed to the public. By allowing a destination path to be included with the filename, similar to how drush does it, can make this more secure.

**Comment by yorkshire-pudding** [comment]
@herbdool - `file` is an optional argument for `db-export`

I always do
```
bee db-export ../db/db-export.sql
```

see https://github.com/backdrop-contrib/bee/wiki/Usage#db-export for full details

**Comment by yorkshire-pudding** [comment]
It also works with absolute refences too
```
lando bee db-export /app/db/db-export.sql
```

or 

```
bee db-export /home/project/db/db-export.sql
```

**Comment by herbdool** [comment]
I tested again and see that it works. I must have done something else wrong the first time. I hadn't noticed there was a wiki, so had gone to the codebase. It looked like it should have worked (and it did).
