### ISSUE TITLE
Output where downloaded modules downloaded to

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#33]
When downloading a module (or other project), it'd be nice to see where it was downloaded to. This is particularly useful with multisites.

Current output:
>  [v]   webform downloaded!

Ideal output:
>  [v]   webform downloaded to /modules!

**Comment by ghost** [comment]
Here's a [PR](https://github.com/backdrop-contrib/b/pull/34) that outputs the following on successful download:

>  [v]   webform downloaded to /[SNIP]/modules/webform!

**Comment by indigoxela** [comment]
@BWPanda works like a charm. ;)
