### ISSUE TITLE
Exit gracefully with a message if admin has put bee in browser accessible place and user accesses bee.php

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#333]
If bee if placed in a browser accessible place (e.g. within the backdrop webroot) then bee tries to execute if someone navigates to bee.php.

This is the result

<details>

#!/usr/bin/env php foreach() argument must be of type array|object, null given /app/backdrop/bee/includes/command.inc:13 [1mBee[0m Usage: bee [global-options] [options] [arguments] [1mGlobal Options:[0m [1;34m--root[0m Specify the root directory of the Backdrop installation to use. If not set, will try to find the Backdrop installation automatically based on the current directory. [1;34m--site[0m Specify the directory name or URL of the Backdrop site to use (as defined in 'sites.php'). If not set, will try to find the Backdrop site automatically based on the current directory. [1;34m--base-url[0m Specify the base URL of the Backdrop site, such as https://example.com/backdrop. May be useful with commands that output URLs to pages on the site. [1;34m--yes, -y[0m Answer 'yes' to questions without prompting. [1;34m--debug, -d[0m Enables 'debug' mode, in which 'log' type messages will be displayed (in addition to all other messages). [1mCommands:[0m CONFIGURATION [1;34m config-export[0m Export config from the site. [1;35m cex, bcex[0m [1;34m config-get[0m Get the value of a specific config option, or view all the config options in a given file. [1;35m cget[0m [1;34m config-import[0m Import config into the site. [1;35m cim, bcim[0m [1;34m config-set[0m Set the value of an option in a config file. [1;35m cset[0m CORE [1;34m download-core[0m Download Backdrop core. [1;35m dl-core[0m [1;34m install[0m Install Backdrop and setup a new site. [1;35m si, site-install[0m DATABASE [1;34m db-drop[0m Drop the current database and recreate an empty database with the same details. This could be used prior to import if the target database has more tables than the source database. [1;35m sql-drop[0m [1;34m db-export[0m Export the database as a compressed SQL file. This uses the --no-tablespaces option by default. [1;35m dbex, db-dump, sql-export, sql-dump[0m [1;34m db-import[0m Import an SQL file into the current database. [1;35m dbim, sql-import[0m INFORMATION [1;34m help[0m Provide help and examples for 'bee' and its commands. [1;34m log[0m Show database log messages. [1;35m ws, dblog, watchdog-show[0m [1;34m status[0m Provides an overview of the current Backdrop installation/site. [1;35m st, info, core-status[0m [1;34m version[0m Display the current version of Bee. MISCELLANEOUS [1;34m cache-clear[0m Clear a specific cache, or all Backdrop caches. [1;35m cc[0m [1;34m cron[0m Run cron. [1;34m maintenance-mode[0m Enable or disable maintenance mode for Backdrop. [1;35m mm[0m [1;34m poem[0m Displays a customised poem. [1;35m p[0m PROJECTS [1;34m disable[0m Disable one or more projects (modules, themes, layouts). [1;35m dis, pm-disable[0m [1;34m download[0m Download Backdrop contrib projects. [1;35m dl, pm-download[0m [1;34m enable[0m Enable one or more projects (modules, themes, layouts). [1;35m en, pm-enable[0m [1;34m projects[0m Display information about available projects (modules, themes, layouts). [1;35m pml, pmi, project, pm-list, pm-info[0m [1;34m uninstall[0m Uninstall one or more modules. [1;35m pmu, pm-uninstall[0m STATE [1;34m state-get[0m Get the value of a Backdrop state. [1;35m sg, sget[0m [1;34m state-set[0m Set the value of an existing Backdrop state. [1;35m ss, sset[0m THEMES [1;34m theme-admin[0m Set the admin theme. [1;35m admin-theme[0m [1;34m theme-default[0m Set the default theme. [1;35m default-theme[0m UPDATE [1;34m update-db[0m Show, and optionally apply, all pending database updates. [1;35m updb, updbst, updatedb, updatedb-status[0m USERS [1;34m user-add-role[0m Add role to user. [1;35m urole, urol[0m [1;34m user-block[0m Block a user. [1;35m ublk[0m [1;34m user-cancel[0m Cancel/remove a user. [1;35m ucan[0m [1;34m user-create[0m Create a user account with the specified name. [1;35m ucrt[0m [1;34m user-login[0m Display a login link for a given user. [1;35m uli[0m [1;34m user-password[0m Reset the login password for a given user. [1;35m upw, upwd[0m [1;34m user-remove-role[0m Remove a role from a user. [1;35m urrole, urrol[0m [1;34m user-unblock[0m Unblock a user. [1;35m uublk[0m [1;34m users[0m List all user accounts. [1;35m uls, user-list[0m ADVANCED [1;34m db-query[0m Execute a query using db_query(). [1;35m dbq[0m [1;34m eval[0m Evaluate (run/execute) arbitrary PHP code after bootstrapping Backdrop. [1;35m ev, php-eval[0m [1;34m php-script[0m Execute an arbitrary PHP file after bootstrapping Backdrop. [1;35m scr[0m [1;34m sql[0m Open an SQL command-line interface using Backdrop's database credentials. [1;35m sqlc, sql-cli, db-cli[0m

</details>

While the guidance recommends placing in the `~/bee` folder, there is currently nothing stopping someone putting it in a web accessible place.

We should exit as gracefully as we can in the browser and also put a warning in the command line.

**Comment by yorkshire-pudding** [comment]
I've replicated the `backdrop_is_cli()` function as the test. I've added some HTML so it looks friendly. I've added a warning message within bee if it detects that it is inside the webroot and I've made it clearer in the README.

This is what it looks like in the browser now:

![image](https://github.com/backdrop-contrib/bee/assets/20357797/06eca990-9d04-443a-9109-63c33f1de07c)

**Comment by izmeez** [comment]
I haven't tested it but I'm assuming this won't happen with Apache if there is a .htaccess rule to protect browser access to it.

**Comment by izmeez** [comment]
This solution seems to be for the benefit of a benevolent user, whereas if it is a prowler it may be giving them more info. Why not simply `die()` and use the Readme and the warnings when used on the command line as included in the PR?

**Comment by yorkshire-pudding** [comment]
> I haven't tested it but I'm assuming this won't happen with Apache if there is a .htaccess rule to protect browser access to it.

@izmeez - yes it gives 403 forbidden, but as you point out, this is apache only so I'd still need something for nginx.  I also prefer my user friendly message and this is in line with the desire within the Backdrop community to make error messages meaningful and useful. With PHP being server side, I'm stopping this at the very top of the file. If you believe there is a security risk, please provide the details privately. This is not something that is likely to be found and it is not likely that someone is going to go looking for it.  Also, other than the possibility being raised in a discussion, I'm not aware of any bee users actually doing this.
