### ISSUE TITLE
UI says `Out of date` while `bee updb` - no pending database updates

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/b#335]
After replacing the core directory with 1.26.1 and running the `bee updb` I expected the DB updated, however UI still shows:

![Screenshot 2023-10-09 at 5 56 26 AM](https://github.com/backdrop-contrib/bee/assets/56604405/d9e9a485-c13c-46a4-aeb0-2d4385eaefbc)

even after all cache is cleared.

**Comment by alanmels** [comment]
Pardon, wrong alert as the message is persisting even after running the update via UI, so it's not `bee`'s issue.

**Comment by yorkshire-pudding** [comment]
Thanks for the update.

**Comment by alanmels** [comment]
@yorkshire-pudding, do you know anything about `Out of date` issue related to last release? Is there some type of regression? Did I miss something? Thanks!

**Comment by yorkshire-pudding** [comment]
@alanmels - I'm not aware of any issue. I updated a site yesterday and it did it fine.

**Comment by yorkshire-pudding** [comment]
Out of interest, I just did the following in one of my test lando machines:

1. Update to 1.26.1 in UI but not complete db update in UI
2. run `lando bee updb` and confirm yes
3. Check status report in ui

All updates seem to have run, so must be something else happening.

**Comment by alanmels** [comment]
Auto-magically, it disappeared. Maybe cron triggered something, I don't know. Anyway, thanks for your responses. All is good.
