### ISSUE TITLE
Bee should exit gracefully when in any non-backdrop directory

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/b#338]
This may be a platform specific issue. Testing bee and it works fine on command line in a directory where backdrop is installed. In any other directory, where backdrop is not present, it simply hangs and unable to exit loop with ctrl+x or ctrl+c keys. Only solution is to close the command window.

Drush on the other hand outputs the help, as does wp-cli.

**Comment by yorkshire-pudding** [comment]
@izmeez - where are you using bee? Bee is **NOT** supported on Windows.

I cannot reproduce that condition. I logged into my host (debian based) and from the home directory, ran bee and it shows help.

**Comment by izmeez** [comment]
Thanks for the heads up. Yes, I am currently testing it on a Windows dev setup. Good to know it is a platform issue and I will have to see if we run into other problems.

**Comment by yorkshire-pudding** [comment]
> Thanks for the heads up. Yes, I am currently testing it on a Windows dev setup. Good to know it is a platform issue and I will have to see if we run into other problems.

There are many commands that simply won't work and can't be easily translated.  When I searched for running drush on Windows it says:

> Most Drush commands will run in a Windows CMD shell or PowerShell, but the Git Bash shell provided by the Git for Windows installation is the preferred shell in which to run Drush commands.

It might be worth trying that; if it gives genuine bash commands then it may be a route to Windows compatibility. Let me know how you get on.

**Comment by izmeez** [comment]
Yes, Git bash is my preferred shell on Windows. I have also found that using Git bash if bee is executed outside a backdrop directory the process can be terminated with ctrl+c keys whereas this does not work with Windows command prompt.
