### ISSUE TITLE
Add bee root directory to status report

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/b#343]
It woud be helpful for bee to report its own root directory in the status report; useful particularly if someone has multiple copies of bee. It's a small addition. Useful if one is using one copy of bee across multiple local sites.

To make clear the distinction between bee's root and the site's root, I'm also suggesting changing the latter label to "Site root directory". So, post-change, the `bee status` report would look like this:

```
 Backdrop CMS           1.26.1                                            
 Bee version            1.x-1.x                                           
 Bee root directory     /myuser/Sites/bee                           
 Site root directory    /myuser/Sites/mysite                
 Site type              Single                                            
 Database               mysql                                             
 ...
```

PR to follow.

**Comment by yorkshire-pudding** [comment]
Good idea.
