### ISSUE TITLE
Make PHPCS in workflow show warnings

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#356]
I've noticed that while PHPCS picks up warnings for me locally, it is not running on the workflow.

I see this is down to the `-n` in this line:
https://github.com/backdrop-contrib/bee/blob/588cde181298eb130444cbac14627ec5d93d8795/.github/workflows/phpcs.yml#L31

@indigoxela - was there a particular reason to exclude warnings from the check?

I would personally prefer to have warnings display in the report and try to get all these addressed before the check passes. However, there does seem to be an option to show the warnings without failing the test:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#ignoring-warnings-when-generating-the-exit-code

I think we could add into the command line with:
```bash
--runtime-set ignore_warnings_on_exit TRUE
```
What do you think?

**Comment by indigoxela** [comment]
>  was there a particular reason to exclude warnings from the check?

Nothing weird, just to not start too strict.

Sure, if you feel confident with it, turn warnings on. :+1:

**Comment by yorkshire-pudding** [comment]
I've been working to this standard, and my original work included clearing warnings, so it would be good to maintain that.
