### ISSUE TITLE
Fix/cleanup `dl backdrop` command

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#36]
The download command (`dl`) has a `root` option: https://github.com/backdrop-contrib/b/blob/1.x-1.x/commands/PM/download.b.inc#L22

Considering the main `b` command has this option, does `dl` need it too? What's the purpose/benefit of declaring it twice?

Need to know as a PR I'm working on adds a `url` option to the main command, and I need to know whether to add it to `dl` too (though it seems to work without it...)

**Comment by indigoxela** [comment]
> Does 'dl' need a 'root' option?

It doesn't need one, if you're in the right directory (where settings.php is located).

Regarding your pr for an url option: have you seen my pr for https://github.com/backdrop-contrib/b/issues/12?

If you're after a solution for multisite - we might have it already. ;)

**Comment by ghost** [comment]
The `borg` project (unrelated to the Backdrop.org theme) has arguments common to all commands, and then command-specific arguments. E.g. https://borgbackup.readthedocs.io/en/stable/usage/create.html

My thinking is that `--root` should be a common option for all `b` commands, so it shouldn't need to be declared in `download.b.inc` again.

**Comment by indigoxela** [comment]
> My thinking is that --root should be a common option for all b commands

That makes sense. The root option is already taken care of in b.php's b_init(), using helper functions from includes/filesystem.inc.
I think too, that's the right place, as having the Backdrop root directory (BACKDROP_ROOT) set is important for many/most b commands.
Funny enough, _dl_ is one of the commands, that don't require a backdrop root.

The fact that commands/PM/download.b.inc also handles the "root" option is very likely a left over.

**Comment by ghost** [comment]
I think https://github.com/backdrop-contrib/b/issues/65 is related to this issue, as `dl`'s `root` option is only really used when downloading `backdrop` (there is one place where it's used elsewhere, but I couldn't get it working). So I think both issues need to be tackled at once...

**Comment by ghost** [comment]
https://github.com/backdrop-contrib/b/issues/65 was closed as a duplicate of this one, so we can fix both issues here (e.g. making sure Backdrop can't be downloaded inside an existing Backdrop install).

**Comment by ghost** [comment]
> there is one place where it's used elsewhere, but I couldn't get it working

Figured this out! Seems to be leftover from before `b` had a global `--root` option. Currently if you are outside of a Backdrop install and do `b dl --root=www simplify`, `b_init()` will see the `root` option and `cd` to that dir. Then the `dl` command also sees the `root` option and checks to see if `www/modules` exists. However, because you're already in `www`, it's effectively checking if `www/www/modules` exists (which it doesn't), so the download fails.

Removing the `--root` option from the `dl` command makes `b dl --root=www simplify` work properly, so then `--root` is only needed for downloading Backdrop itself (telling Backdrop where to download to), in which case I think we should rename it to something like `--dir` and describe it as the directory to download Backdrop into. If it's not set, Backdrop's downloaded into the current directory (as long as the current directory isn't within an existing Backdrop installation).

**Comment by ghost** [comment]
Fixing https://github.com/backdrop-contrib/b/issues/6 in this issue too (making sure Backdrop doesn't override an existing installation).

**Comment by ghost** [comment]
Here's a PR: https://github.com/backdrop-contrib/b/pull/100

**Comment by indigoxela** [comment]
@BWPanda your PR works like a charm.

I've been testing stuff related to #6 (unattended overwrite), and that works fine too. :+1:
