### ISSUE TITLE
Add releases so civicrm-buildkit can easily use a specific version

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/b#365]
In https://github.com/civicrm/civicrm-buildkit/edit/master/composer.json, civicrm-buildkit is currently using `drush-backdrop` but it would be better for them to use `bee`. Ideally, it would be good to reference a specific version rather than the latest. @yorkshire-pudding do you think you'd be willing to create releases every so often? The last one was in 2021.

One reason to use a specific version is so that a commit that introduces a bug to bee doesn't break CiviCRM's automated testing.

**Comment by yorkshire-pudding** [comment]
Hi @herbdool - yes. It is definitely something I/we have explored and will look to progress this with a bit more urgency.

**Comment by yorkshire-pudding** [comment]
Completed in https://github.com/backdrop-contrib/bee/releases/tag/1.x-1.0.1
