### ISSUE TITLE
bee status: Notice: Undefined index: port

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/b#371]
When the database port is not explicitly defined the bee status command returns:
`Notice: Undefined index: port in status_bee_callback() ...`
Is this necessary since the system default port is being used?

**Comment by yorkshire-pudding** [comment]
@izmeez - please provide detailed steps to reproduce as I don't get this
![image](https://github.com/backdrop-contrib/bee/assets/20357797/98658fbc-d40e-4cab-9abf-c62f0f59e5cd)

**Comment by izmeez** [comment]
I have tested this again and see the same results on Linux and Winnt systems with the phar and also locally on Winnt with earlier version of bee-1.x-1.x full version. I made an assumption it was related to the database port.
![bee-issue-371-screenshot](https://github.com/backdrop-contrib/bee/assets/6208775/342dc090-c90a-41ea-bdf2-f2bdc2e30af9)

**Comment by yorkshire-pudding** [comment]
@izmeez - Firstly, Windows is NOT supported, so let's just focus on Linux.
What version of PHP are you using?
Do you still get the error with Backdrop 1.27.1 (the latest release) and 1.28.x-dev?
What type of Linux? Is this some form of local environment or your web host?

Thanks

**Comment by izmeez** [comment]
The screen capture in the previous comment is from the web host where Cloud Linux is the OS. Update of Backdrop to 1.27.1 on that server does not make a difference. Also local testing with the 1.28.0-preview makes no difference. I think this is a low priority issue since it does not affect the working of Bee and is more cosmetic. It may have to wait until more details come to light.

**Comment by yorkshire-pudding** [comment]
> The screen capture in the previous comment is from the web host where Cloud Linux is the OS. Update of Backdrop to 1.27.1 on that server does not make a difference. Also local testing with the 1.28.0-preview makes no difference. I think this is a low priority issue since it does not affect the working of Bee and is more cosmetic. It may have to wait until more details come to light.

PHP version?

**Comment by yorkshire-pudding** [comment]
I tested out the code that bee uses in Devel > Execute PHP:

![image](https://github.com/backdrop-contrib/bee/assets/20357797/eac81c9d-0093-44c9-8cb5-ee71ae4289c7)

This is lando and you'll note that `port` exists in the array with a `NULL` value, which is why I don't get that error.
Could you run the same on your site?
Download and enable Devel
Go to 'Devel Tools' > 'Execute PHP'

```php
$db = Database::getConnectionInfo();
dpm($db);
```
Redact any sensitive information from your screenshot.

Was this an upgrade from D7?

**Comment by izmeez** [comment]
PHP 7.4.33 and not an upgrade from D7, The devel output does not show port as it was not included in the settings.php file.
![bee-issue-371-devel-screenshot](https://github.com/backdrop-contrib/bee/assets/6208775/5b10e304-2f9f-411b-8d00-08da16c3f365)

**Comment by izmeez** [comment]
So we know what is causing the message and that Backdrop works without it. Is it worth changing Bee to support if port is not included?

**Comment by indigoxela** [comment]
FWIW, I get the port, too (as NULL). It's on PHP 8.2 on Linux, with MariaDB on the same box (version 10.11). And I get the same output on PHP 7.4. Can this have anything to do with the database server?

**Comment by yorkshire-pudding** [comment]
Right. Here is what is happening. Port is not defined in most `settings.php` files.

This is what it is in Lando:
![image](https://github.com/backdrop-contrib/bee/assets/20357797/54bf8d24-7bad-4725-8bed-2ac87d51d80f)

and this is the default:
![image](https://github.com/backdrop-contrib/bee/assets/20357797/817c9e18-bdc5-4f87-8464-b817b627df00)

So most don't have the port, but they use the `$database` variable and backdrop handles this.
If you use the `$databases['default']['default']` method of defining db credentials (e.g. to cope with complex passwords that the db url can't handle) then Backdrop handles slightly differently and that is why `port` is not in the array if it is not defined.

I've now been able to reproduce using this database setting method, so yes, Bee should be changed to accommodate this.

**Comment by yorkshire-pudding** [comment]
@izmeez - there is now a PR see #373
Please can you test

**Comment by izmeez** [comment]
The PR works as expected, solves the problem and the code looks good. Thank you.
