### ISSUE TITLE
bee help: cols was unexpected at this time

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/b#372]
When using the bee ~~status~~ help command the message `cols was unexpected at this time.` occurs twice: once after `Global Options:` and again after `Commands:`. It is probably because they are simply section headers.

**Comment by yorkshire-pudding** [comment]
@izmeez - please can you provide detailed steps to to reproduce

**Comment by izmeez** [comment]
I have tested this further. My apologies it is not related to the bee status and occurs with bee help. I have identified that it is likely not an issue with bee and is specifically related to the use of a batch file on a WINNT system. This issue should probably be closed. Thank you.

**Comment by yorkshire-pudding** [comment]
Thanks for clarifying.
