### ISSUE TITLE
If a module dependency is in core it assumes it's on contrib

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/b#382]
I've got a module that depends on the core `list` module. Either bee is assuming all dependencies are in contrib, or it can't find some modules if they're embedded in another module. `list` is inside of `field`.

**Comment by yorkshire-pudding** [comment]
@herbdool - I've been able to reproduce this and have created a PR that fixes this.  Please can you test.

**Comment by herbdool** [comment]
@yorkshire-pudding thanks! I've tested and it works. Also reviewed the PR. RTBC
