### ISSUE TITLE
Improve bee site-install to avoid permission error on install.sh script, which often needs execute permissions adding

### ISSUE THREAD

**Issue by gwolf** [backdrop-contrib/b#386]
When attempting to do the site initialization with Bee, it assumes file permissions that don't match that of a just-downloaded Backdrop install:

    /tmp $ mkdir bkdrp
    /tmp $ cd bkdrp/
    /tmp/bkdrp $ bee dl-core
    
     [✔] Backdrop was downloaded into '/tmp/bkdrp'.
    
    /tmp/bkdrp $ bee site-install --auto --db-name foo --db-user foo --db-pass foo
    
    Installing Backdrop. This may take a moment...
    
    sh: 1: ./core/scripts/install.sh: Permission denied

This is easily fixed by issuing a `chmod 0755 core/scripts/install.sh`. I guess a cleaner way would be to modify `install.bee.inc` to explicitly call the PHP binary that's already being used instead of calling the PHP interpreter with the `install.sh` script as an argument.

**Comment by yorkshire-pudding** [comment]
Hi @gwolf - welcome to Backdrop and Bee.
I do the `chmod` nearly all the time for new sites.  Yes, it could be re-written to avoid that script.  I've marked it as an enhancement and re-titled it.  I can't promise anything about when it might get done though, as I'm working on other `bee` priorities at the moment, when I can spare the time.
