### ISSUE TITLE
site_install.b.inc return TRUE on site_install_b_callback

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-contrib/b#4]
b_render() is looking for render structure returned by callback.

site_install_b_callback return TRUE and it get rendered as 1.

Need to be fixed.

```
Castle:b gor$ php b.php si --root="/www/bd1.2/" --db-url="mysql://root:@127.0.0.1/bd"
Installing Backdrop. This may take a moment...
 [o]   Backdrop installed successfully.

1
```

Will fix it when @serundeputy finish major cleanup to do not get into merge issues.

**Comment by ghost** [comment]
The recent re-write fixed this.
