### ISSUE TITLE
Update symbols used in messages

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#40]
Currently the following symbols are used in messages:

- `o`: status
- `v`: success
- `!`: warning
- `x`: error
- `-`: log

Most of these are ok, once you get used to them (and the colours certainly help too), but some aren't obvious to start with and can be confusing. E.g. I guess `v` is meant to be a check mark...?

In setting up tests for this project, I noticed that PHPUnit's TestDox output uses nice symbols in the command line. They [have](https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/TestDox/CliTestDoxPrinter.php#L56):

- `✔`: passed
- `✘`: error/failure
- `↩`: skipped
- `☢`: risky
- `∅`: incomplete
- `⚠`: warning
- `?`: unknown

Those (the first two at least) are clear and un-ambiguous. I was thinking we could use the same/similar symbols for ours... Something like:

- `●`: status
- `✔`: success
- `❗`: warning
- `✘`: error
- `⚑`: log

**Comment by indigoxela** [comment]
While your symbols sure look better, there's a possible glitch:

Currently b uses ASCII, you suggest UTF8 chars. This might be a problem in some environments.

**Comment by ghost** [comment]
I was wondering about that, but I figured if PHPUnit uses them then they should be ok right?

**Comment by ghost** [comment]
I'm including this as part of https://github.com/backdrop-contrib/b/issues/5
