### ISSUE TITLE
Errors shown when they shouldn't be

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#41]
When running `b cron` I got the following error:

```
stat(): stat failed for /tmp/update-cache-38df50e0
	/app/www/core/includes/stream_wrappers.inc:836
```

The code in question is this:

```
// Suppress warnings if requested or if the file or directory does not
// exist. This is consistent with PHP's plain filesystem stream wrapper.
if ($flags & STREAM_URL_STAT_QUIET || !file_exists($path)) {
  return @stat($path);
}
```

In reading up on the `@` symbol before the function call, I found this:

> If you have set a custom error handler function with set_error_handler() then it will still get called, but this custom error handler can (and should) call error_reporting() which will return 0 when the call that triggered the error was preceded by an @.

(source: https://www.php.net/manual/en/language.operators.errorcontrol.php)

We do indeed set a custom error handler, which outputs error messages regardless. I think we should wrap the error output in a check to make sure `error_reporting()` is not '0' so that suppressed errors won't be shown.

**Comment by ghost** [comment]
[PR](https://github.com/backdrop-contrib/b/pull/42/files)

**Comment by indigoxela** [comment]
@BWPanda good catch! I can confirm, you PR prevents these errors from showing on cron runs.
