### ISSUE TITLE
If user adds wrong argument/option show help for command

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#424]
As a bee user
When I type the wrong arguments or options or miss them
Then as well as the error, bee should show the help for the command

**Comment by stpaultim** [comment]
Great idea! Would help me.

**Comment by yorkshire-pudding** [comment]
Hi @stpaultim - care to check out the PR

**Comment by stpaultim** [comment]
Once again. Finally tested the PR after it was merged! Nice work.
