### ISSUE TITLE
Don't display success message if cron doesn't run

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#43]
Currently, a success message is displayed regardless of whether cron actually runs when using the `b cron` command. We should check the return status of `backdrop_cron_run()` and display a message appropriately.

**Comment by ghost** [comment]
[PR](https://github.com/backdrop-contrib/b/pull/44)

**Comment by indigoxela** [comment]
@BWPanda yet another good catch! But I do have concerns regarding the failure message (wording), see my comment on your PR.
