### ISSUE TITLE
Update install instruction for bee on DDEV

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#447]
This issue in the the DDEV queue:
https://github.com/ddev/ddev/issues/5740

Has been addressed with the release of this DDEV addon by @jenlampton 
https://github.com/jenlampton/ddev-backdrop-bee

There are instructions:

> 1. Install this addon with `ddev get jenlampton/ddev-backdrop-bee`.
> 2. Restart DDEV with `ddev restart`.
> 3. Test bee by running `ddev bee status`.

@jenlampton has said the ambition is to move this into backdrop-ops so it may be worth hanging on with the change until that move happens.

**Comment by jenlampton** [comment]
I have moved the project to https://github.com/backdrop-ops/ddev-backdrop-bee. 

The instructions: have changed to

> 1. Install this addon with `ddev get backdrop-ops/ddev-backdrop-bee`.
> 2. Restart DDEV with `ddev restart`.
> 3. Test bee by running `ddev bee status`.

**Comment by yorkshire-pudding** [comment]
Closed via c0c14fe

**Comment by jenlampton** [comment]
Looks like the command has changed to `ddev add-on get backdrop-ops/ddev-backdrop-bee.`

**Comment by yorkshire-pudding** [comment]
Thanks @jenlampton - updated in [52935c2](https://github.com/backdrop-contrib/bee/commit/52935c245d4b7e2bc829e3fa25422e0a5d0f13a7)
