### ISSUE TITLE
Watchdog shows earliest messages, not latest

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#47]
Despite the fact that the `watchdog-show` command help text says of the `wip` argument:

> If not provided, a listing of most recent 10 messages will be displayed.

It only shows the 10 earliest commands, not the latest. I think we need to sort the data before printing...

**Comment by ghost** [comment]
[PR](https://github.com/backdrop-contrib/b/pull/48)

**Comment by indigoxela** [comment]
@BWPanda yet another fix? Wow!
Confirmed: sorting is wrong and your PR fixes that.

Add two quotation marks and php is happy (see comment there).

**Comment by ghost** [comment]
@indigoxela Yeah I'm writing tests for `b`, so coming across all sorts of bugs :wink:
