### ISSUE TITLE
Disallow multiple callbacks per command (and other architectural changes)

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-contrib/b#5]
I thought it would be nice to have multiple callbacks per one command but then there is not clear behaviour when you do `b en project_name`

there are two callbacks: 
- module.b.inc 
- theme.b.inc

Each one check if there is module (theme) like project_name and if yes, it enables it.

But if there is no such a project, then there is no message about it.

It’s a result of not really clean architecture.

Have no clue yet which direction to go:
- allow only one handler by command name: then this handler will message 'no project like this'
- somehow detect if no one command reacted and write message 'something is wrong here'
- something else

Splitting to different modules sounds cool to me because we can have separated code to do:
- `b en layout_name` (—layout related options)
- `b en module_name`
- `b en theme_name` (—admin to set as admin —default to set as default)

Backdrop has layouts. They required different approach (enable mean attach layout template to layout)

If we choose to have only one handler per command, then we have to add:
-  theme-enable (ten alias?) 
- layout-template-enable (lten ?) 

and then what to do with pm—list (pml)? 
It does not make sense list modules, themes and layouts there then.

Also, I think about commands name. They should be similar to drush. To make migration process as easy as possible.

**Comment by Gormartsen** [comment]
One of the main idea on my side is all b_like behaviors should mirror backdrop: messages, hooks, render and etc.

b_set_message is mirroring backdrop_set_message
bt() is mirroring t()
and so on.

so, when somebody start to code for console only, he has almost 0 adoption period.

hook_b_command looks like hook_menu.

I think we should rewrite command processor to treat hook_b_command similar to hook_menu.

It means that we need to have separated commands for modules, themes and layouts:
theme-enable/disable
layout-enable/disable
module-enable/disable
theme-list
layout-list
module-list

UX will change for `pml` then. That's bad from one side, but it is good from another.
We can focus module, theme and layout listings to be more specific.

**Comment by jlfranklin** [comment]
Only one handler per command is the only sane way to handle it.  However, there is no reason that handler could not invoke hooks or have the `*.b.inc` files register callbacks that are then tried sequentially until one of them returns a result.  Consider, for example, the `en` command.  The callbacks could return `TRUE` (found, enabled), `FALSE` (found, failed to enable), and `NULL` (didn't find anything, continue with the next one.)

**Comment by ghost** [comment]
I was always confused by the duplicate `core-status` commands in `status.b.inc` and `test.b.inc`. Now, after reading through and getting my head around this issue, I understand why/how they work like that!

Yes, I agree this is not only problematic for implementing certain things (returns, errors, project-type-specific options, etc.) but also confusing to developers (like me!).

I like @jlfranklin's idea of a single callback that processes all `en` commands, but calls different functions in the module/theme/layout `.b.inc` files that do their own processing and return a value appropriately. Would this work regarding different options for different project types though...?

**Comment by ghost** [comment]
I've been wanting to go through the code and do some cleanup, rewriting, etc. and this issue has given me the excuse to do that. Apart from rewriting the command hooks to disallow multiple callbacks per command, I'm also doing things like making sure `bt()` is used correctly and consistently, adding better/proper documentation to functions, rewriting code to be simpler, more streamlined, more readable, etc.

**Comment by ghost** [comment]
Just over 1 year later and it's done! 😄
