### ISSUE TITLE
Rename `b` to `bacon`?

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/b#59]
Per [Olafski's recommendation](https://forum.backdropcms.org/forum/renaming-backdrop-consoles-cli-shorthand-brush?page=0%2C0#comment-1350) I'm copying the forum thread to the project's issues.

Starting to work with Backdrop Console, I find its command line shorthand **_b_** convenient, yet little bit odd and not so appealing. I believe making it slightly longer, but self-explanatory at first sight, would serve for the Backdrop community members' convenience. 

For example, **_b_** could become two the letter abbreviation of Backdrop Console **_bc_**, or three letter abbreviation **_bdc_** or, in Drupal Console's manner, the full word **_backdrop_**. But I do believe the most striking and appealing command would be just **_brush_**!

Despite some users might find the word **_brush_** used as a command-line tool little funny, its verb definitions suit to and are descriptive what **Backdrop Console** should also be about:

> brush (verb)
> 
> 1. remove (dust or dirt) by sweeping or scrubbing.
> 
> 2. touch lightly and gently.

The **_brush_** command would also be easy to differentiate and switch for those who are coming with Drupal 7 background are used to **_drush_**.

Any thoughts on this?

**Comment by alanmels** [comment]
And for completeness of the discussion's move from the forum, here is another [useful reference](https://forum.backdropcms.org/comment/1353#comment-1353) from the same forum thread, this time from @klonos:

> Not the first time the name "brush" comes up as a suggestion :) (https://github.com/backdrop/backdrop-issues/issues/47#issuecomment-24275176 back in 2013 for example).

So despite his skepticism about the idea, the copyright for the first use of **_brush_** goes to @greg-1-anderson ;)

**Comment by ghost** [comment]
I do like the name `brush`, so much so that I already suggested it for Backdrop's Drush: https://github.com/backdrop-contrib/drush/issues/184#issuecomment-511666179 :smile:

Not sure about changing the `b` command though, i like the simplicity of it. I'll let the other maintainers weigh in...

**Comment by alanmels** [comment]
Peter, thanks for the link. Yet another relevant and useful discussion.

**Comment by alanmels** [comment]
For now I've done:

```
git clone https://github.com/backdrop-contrib/b.git
mv b brush
```

then sourced the new alias:

```
alias brush='php /path/to/brush/b.php'
```

on my local environment, and am now happily brushing my Backdrop setup ;)

**Comment by greg-1-anderson** [comment]
Not up to speed here, but if you're starting a cli basically from scratch, see https://github.com/g1a/starter

**Comment by Radcliffe** [comment]
As **drush** is a portmanteau of Drupal shell, I suggest the name **bacon** for the Backdrop console. I would not use **bc** because it conflicts with the Unix command-line calculator utility.

**Comment by alanmels** [comment]
`Bacon` also sounds very appealing and straightforward evident abbreviation of **Bac**kdrop **Con**sole.

As for `Brush`, if the letter `r` looks somehow disconcerting, it is also there present in the portmanteau of **B**ackd**R**op **sh**ell. There is no `u` though, but if being so strict, we could go with `brosh` then ;) Sounds crazier, but why not?!

But then I like `bacon` more than `brosh`.

**Comment by AlexShapka** [comment]
+1 for `bacon` for Backdrop Console. `brosh` or `brush` better suits for https://github.com/backdrop-contrib/drush if it ever will be renamed as discussed on https://github.com/backdrop-contrib/drush/issues/184

**Comment by ghost** [comment]
I checked with @serundeputy and, like me, he feels we shouldn't rename `b`.

`b` is simple and easy to use/type as it is now. If anyone wants to use a different name/command, they should feel free to do as @alanmels did [above](https://github.com/backdrop-contrib/b/issues/59#issuecomment-542821179) and create their own, custom alias for `b`.

Thanks for the suggestions all, but closing as 'won't fix'.

**Comment by alanmels** [comment]
Fair enough. It was just an idea to explore. Aliasing per everyones liking indeed works just fine.
