### ISSUE TITLE
b dl backdrop tries to overwrite if there is already a dir named backdrop.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/b#6]
if there is an existing `backdrop` installation in the same directory as the command `b dl backdrop` is issued, then it tries to overwrite the existing install.

We should:
1. Check if there is already a directory called backdrop and inform the user.
2. Optionally allow the user to download to a sub directory like:
   - `b dl backdrop --dir={my-backdrop}`
     - where of course `{my-backdrop}` is replaced by the dir the user wants to use.

**Comment by Gormartsen** [comment]
1. With latest #7 there is check for destination folder and it will display error message if backdrop exists.
2. if --root="dir" provided, it will download backdrop to {dir}/backdrop . I am still not happy with this one.

I personally dislike when `drush dl drupal`  did not have option to copy content to current directory.
I always had to move it by myself.

So I want to have an option to do b dl backdrop --here and it will move backdrop/* to ./ right after it has been downloaded.

**Comment by ghost** [comment]
Going to fix this as part of https://github.com/backdrop-contrib/b/issues/36.
