### ISSUE TITLE
Issue with enabling a project

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#62]
When testing enabling, disabling and uninstalling a module repeatedly, I had an issue where the module wasn't being enabled, and there was no output from the command.

I tracked it down to the fact that the DB didn't have a record of the module, even though it existed in the file system (and the DB is where the code checks for modules to enable).

**Comment by ghost** [comment]
[PR](https://github.com/backdrop-contrib/b/pull/63) fixes this by rescanning for modules before enabling them.

**Comment by indigoxela** [comment]
Didn't test that yet, but I wonder, if function _enable_project() needs to consider themes and layouts as well.

The naming of functions and/or the options in modules.b.inc are a bit confusing for me.
For instance function modules_b_command() offers options to

> 'Filter by extension type. Choices: module, theme, layout.'

While neither the filename nor the function name indicate that this command also covers themes and layouts.

**Comment by ghost** [comment]
Same thing just happened to me with themes, so updated the PR accordingly.

**Comment by ghost** [comment]
> I wonder, if function _enable_project() needs to consider themes and layouts as well.

I created an issue for that: https://github.com/backdrop-contrib/b/issues/67
It was obviously the original function, before they realised that themes are slightly different. And since layouts don't really get 'enabled' or 'disabled' then that function is just for modules now.

> For instance function modules_b_command() offers options to
'Filter by extension type. Choices: module, theme, layout.'

Yeah, that `pm-list` command is kind of a generic one that applies to all projects, whereas the others are module or theme-specific. Can't really move `pm-list` to the `download.b.inc` file as that wouldn't make sense either...

**Comment by ghost** [comment]
Ooh, I know: https://github.com/backdrop-contrib/b/issues/68
