### ISSUE TITLE
Downloading Backdrop from within Backdrop

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#65]
When you're in a Backdrop site and run `b dl backdrop`, what should happen?

Currently it downloads Backdrop inside itself. E.g.:

```
backdrop
  core
  files
  ...
core
files
...
```

I suggest preventing this and displaying a message saying that you can't download Backdrop within Backdrop. You should run `b dl backdrop` outside of an existing Backdrop installation, or use the `--root` option to specify the download location.

**Comment by indigoxela** [comment]
@BWPanda you're of course right, b shouldn't download a Backdrop inside another one.

**Comment by ghost** [comment]
Going to close this as a duplicate of https://github.com/backdrop-contrib/b/issues/36 since the fix for both can be worked on at the same time in the one PR.
