### ISSUE TITLE
b doesn't recognize release

### ISSUE THREAD

**Issue by AlexShapka** [backdrop-contrib/b#66]
When trying to download the `search_krumo` module `b` complains there is no release and offers to download *git* version instead:

```
docker@cli:/var/www/docroot/modules$ b dl search_krumo
There is no release for backdrop-contrib/search_krumo
Do you you want to download *git* version instead? (y/N): 
```

however as https://github.com/backdrop-contrib/search_krumo/releases shows there is in fact a release tagged as `1.x-1.0.0`. 

Have I done something wrong when creating that release per instructions on https://help.github.com/en/articles/creating-releases or it's `b`'s issue? I did not upload binary files, but the instruction page says that field is optional.

**Comment by indigoxela** [comment]
@AlexShapka it doesn't seem to be related to b(acon)...

This release zip file should get created automatically. If it exists for a project, the download with b works fine.
I wonder, why your search_krumo.zip wasn't created.

**Comment by AlexShapka** [comment]
@indigoxela, thanks for your input.

> This release zip file should get created automatically. If it exists for a project, the download with b works fine.
> I wonder, why your search_krumo.zip wasn't created.

Reading the https://help.github.com/en/articles/creating-releases carefully once again, I have no idea what's wrong with https://github.com/backdrop-contrib/search_krumo/releases/tag/1.x-1.0.0 :(

**Comment by indigoxela** [comment]
> I have no idea what's wrong with...

Wild guessing: your .info file contains `version = VERSION`. Probably the packaging script chokes on that?

See: https://api.backdropcms.org/modules#info-files

Try to remove that line an create a new release.

**Comment by AlexShapka** [comment]
> > I have no idea what's wrong with...
> 
> Wild guessing: your .info file contains `version = VERSION`. Probably the packaging script chokes on that?
> 
> See: https://api.backdropcms.org/modules#info-files
> 
> Try to remove that line an create a new release.

Bingo, @indigoxela, as https://github.com/backdrop-contrib/search_krumo/releases/tag/1.x-1.0.1 now has automatically generated .zip file and the `b dl search_krumo` worked like a charm:

```
docker@cli:/var/www/docroot$ brush dl search_krumo
 [v]   search_krumo downloaded to /var/www/docroot/modules/search_krumo! 

docker@cli:/var/www/docroot$ 
```

Thanks for the hint!

**Comment by AlexShapka** [comment]
I wonder is there any way to give credits for this kind of help when fixing issues?

**Comment by klonos** [comment]
> I wonder is there any way to give credits for this kind of help when fixing issues?

You can try `++`'ing @indigoxela on Gitter; it will give karma points 🙂

**Comment by AlexShapka** [comment]
> > I wonder is there any way to give credits for this kind of help when fixing issues?
> 
> You can try `++`'ing @indigoxela on Gitter; it will give karma points 🙂

I've just tried with no luck. Probably I do not have enough permission level
