### ISSUE TITLE
Move `pm-list` to new `list.b.inc` file

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#68]
Since `pm-list` is a type-agnostic command (applies to modules, themes and layouts), then it shouldn't be in `module.b.inc`. We should move it to `download.b.inc` (where `pm-download` is also type-agnostic) and rename that file to `pm.b.inc`.

**Comment by serundeputy** [comment]
I think I'd prefer to have `pm-list` in its own file maybe `list.b.inc` as download is well named download and is complicated enough in it's own right.

What do you think @BWPanda ?

**Comment by ghost** [comment]
Sure, that works too.

**Comment by ghost** [comment]
I think this should wait to see what we decide regarding https://github.com/backdrop-contrib/b/issues/5...

**Comment by ghost** [comment]
`pm-list` (a.k.a. `projects`) is now in `projects.b.inc`, along with the enable, disable, etc. commands (i.e. all project-related functionality).
