### ISSUE TITLE
Adhere to coding standards

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#73]
Now that Travis CI checks the code against Backdrop's coding standards, we should fix the code to adhere to them :smile:

**Comment by serundeputy** [comment]
- [x] fixed `commands/PM/download.b.inc` in #74 
- [x] fixed `commands/PM/modules.b.inc` in #75 
- [x] fixed `commands/PM/themes.b.inc` in https://github.com/backdrop-contrib/b/pull/76
- [x] `commands/Help`
  - [x] `drush_help.drush.inc` https://github.com/backdrop-contrib/b/pull/77
  - [x] `help.b.inc` https://github.com/backdrop-contrib/b/pull/78
