### ISSUE TITLE
Change the 'BackdropCMS is not installed yet' message

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#83]
In `b.php` if the database cannot be connected to (e.g. no valid `settings.php` file found), it displays this warning:

> BackdropCMS is not installed yet.

This is particularly confusing in a multisite setup as Backdrop *is* installed, just elsewhere in the `/sites/*` directory.

We should either:

- Re-word this message to be more helpful
- Only display this message if `debug` is turned on

**Comment by ghost** [comment]
Here's a PR that displays a different message if it's a multisite (that hopefully makes more sense): https://github.com/backdrop-contrib/b/pull/98/files

**Comment by indigoxela** [comment]
Yep, very helpful.

I tested with existing and non-existing "multisites" (entry not in sites.php, entry in sites.php but no directory, and variants)

Maybe a little verbose, when the site from provided --url param isn't listed in sites.php (total garbage / typo...)
```
 [x]   multi3.domain.tld could not be found in ...html/sites/sites.php.                                      
 [x]   Required bootstrap level for status is not ready                                                                      
 [!]   The Backdrop site within the multisite installation could not be determined. Some functionality may not be available. 
 [o]   Backdrop multisite installation detected.
```                                                                             
But helpful for sure.

**Comment by ghost** [comment]
Thanks @indigoxela. Maybe a [separate issue](https://github.com/backdrop-contrib/b/issues/101) for better messages/reducing similar/unnecessary messages is needed, but glad this is working better now.
