### ISSUE TITLE
Handle --url and --root better

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#85]
Currently, if you run `b` from one Backdrop installation but specify `--root` to point to another Backdrop installation, you'll get this message:

> Current directory and --root don't match. Please change to a directory under --root or remove --root option.

We should re-word this message to be more understandable, or work out how to handle this situation better (e.g. require `--url` if `--root` is specified?).

**Comment by indigoxela** [comment]
I'd like to enhance b, so it behaves more like drush.
... if I'm fast enough to keep up with your development tempo. @BWPanda 

To my opinion b should run smoothly in following situations:

- From _anywhere_ inside a Backdrop install, without any additional option
- From outside, if a "--root" option to a directory is provided and there's a settings.php

It's not the wording, it's actually the functionality I'd like to improve.

**Comment by indigoxela** [comment]
I'm pretty sure, this is not as intended:

```
.../b/b.php --root=/var/www/backdrop/html st
 [x]   Current directory and --root don't match. Please change to a directory under --root or remove --root option. 
 [o]   Backdrop CMS Installation detected; wooot;                                                                   

 Backdrop CMS       :  1.14.1                 
 Backdrop root      :  /var/www/backdrop/html 
 Database driver    :  mysql                  
 Database host      :  127.0.0.1              
 Database name      :  backdrop               
 Database username  :  backdrop               
```

I'm told to change directory, but b runs fine.
I suspect, this check isn't needed anyway or should be slightly different:
https://github.com/backdrop-contrib/b/blob/8e40c2ff38c9c30cf371dfee05c1936eee1e1d1c/includes/filesystem.inc#L363

Before I provide a PR: what's the intention of this check anyway? Which b command needs this?

**Comment by ghost** [comment]
The purpose of this check is to make sure the site dir is in the same installation as the root dir.

If you're in `/var/www/bd-dev` and you run `b --root=/var/www/bd-stg st` it'll display the warning but still work. This is because you haven't specified the `--url`, so it checks the current dir for `settings.php`. But that `settings.php` is in a different installation than the `--root` you specified. So it warns you but still runs the command from the root installation anyway.

This probably seems unnecessary with regular installs, but with multisite installs it can have issues, hence the check. But it can definitely be improved.

**Comment by indigoxela** [comment]
Ah, I get it. Btw. this could also be relevant for regular installs regarding downloads.

One could be inside a Backdrop install and call another one with the "--root" option. So where should a module get downloaded - here or there...
I'd suppose "there". If a root option is set, this option has precedence over the current directory - would you agree with that?

If _outside_ any Backdrop install (somewhere in the filesystem), the download should go to the current directory, right? (Like drush does it)

Now, if it comes to multisite, things get a little more complex regarding downloads.
If "--root" is set, this has precedence, too. But the directory to download stuff might or might not need a "--url" option. We could download to the main /modules, or to /sites/foobar/modules, or /sites/baz/modules... What could be a reliable way to determine the correct target directory?
We might need some sort of dialog (b_choice()), if "--url" isn't set. Or is this overdone?

@BWPanda what do you think?

**Comment by ghost** [comment]
> If a root option is set, this option has precedence over the current directory - would you agree with that?

Yes.

> If outside any Backdrop install (somewhere in the filesystem), the download should go to the current directory, right?

Probably, especially if you `b dl backdrop` :-)

> Now, if it comes to multisite...

If `--url` isn't specified, downloads should go to the Backdrop root directories. There's no way to know what site to download to without the user specifying, and they have `--url` for that, so if they don't use it then it's a generic download.

**Comment by indigoxela** [comment]
> ...they have --url for that, so if they don't use it then it's a generic download.

That makes sense, agreed!

**Comment by indigoxela** [comment]
I played with all sorts of combinations of "--root" and "--url" from inside/outside with single site / multisite.

Hey, that rocks!

The only thing not perfect yet, is that misleading message "Current directory and --root don't match. Please...".
It doesn't do any harm, if one calls b from anywhere else, including other Backdrop installs.

Tested with st / updb / dl. So that check may be redundant anyway.

**Comment by ghost** [comment]
So after looking back over this again to refresh myself, I think I've worked out a fix...

Firstly, to explain; the message in question refers to trying to find the 'site' (a.k.a. multisite) of a Backdrop installation, as some commands need that in multisite setups. It only appears if you set the `--root` option, but not the `--url` option. Presumably you don't set the `--root` option if you're already in the currect Backdrop installation, so setting `--root` means either you're currently in a different installation than the one you want, or you're not in any Backdrop installation. Either way, by not setting the `--url` option it's impossible to tell what (multi)site to apply the command to, so we just apply it to Backdrop root instead (if applicable). That's where this message came in. The idea was to tell you about this discrepancy between the current directory and the `--root` directory.

But I worked out a better (simpler) solution. We just simply don't check for (multi)sites if you haven't specified `--url` but you have specified `--root`. In that case, commands are just applied to the `--root` you specify and `BACKDROP_SITE` isn't defined (which is all that can be expected I think).

Testing welcome!

**Comment by ghost** [comment]
@indigoxela Are you willing/able to test this for me? If it works as expected then I'll merge as something else I'm working on will require this fix I believe...

**Comment by indigoxela** [comment]
Better don't merge yet, I seem to have found some issues...

When running with "--root=/path/to/backdropsite" against a single site install:

`Undefined variable: _backdrop_site  .../b.php:97`

(outside or inside install doesn't matter.)

When running with a combination of --root plus --url to a multisite install:
```
 [!]   No Backdrop installation found. :(               
 [x]   Required bootstrap level for status is not ready 
```
This _might_ be intentional, but doesn't seem right to me, because I can't run "b" on a multisite from outside that multisite install then. (Like I can run it on a single site install from everywhere in the file system.)

Ehem, to be honest, I read your recent comment several times, but I'm not really sure, what it means :wink:

**Comment by ghost** [comment]
@indigoxela Thanks for the review. I've made a commit to the PR that fixes an oversight on my part (fixes `Undefined variable`). I then tested your second problem ("combination of --root plus --url"), and that's working fine for me, so could you please test again with the latest commit and see if that fixes both issues for you?

**Comment by indigoxela** [comment]
> (fixes Undefined variable)

Yes, that's fixed.

Re combination of --root plus --url on multisite:

No changes here.
`b st --root=/path/to/html/sites/multi1 --url=multi1.domain.tld`
Still outputs:
```
 [!]   No Backdrop installation found. :(               
 [x]   Required bootstrap level for status is not ready 
```
...from anywhere outside or inside that multisite. I double checked that path and url are correct.

**Comment by ghost** [comment]
Ah, `--root` should point to the Backdrop root dir, not the site root dir.

**Comment by ghost** [comment]
So you need `b st --root=/path/to/html --url=multi1.domain.tld`

**Comment by indigoxela** [comment]
> So you need b st --root=/path/to/html --url=multi1.domain.tld

Ah, got it! Yes, that's working fine.
