### ISSUE TITLE
`dl` doesn't create a project-type folder if it doesn't exist

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#90]
I just tried running `b dl bamboo` which didn't work.

Bamboo is a layout, and I didn't already have a `layouts` folder in my multisite, so I got a bunch of `failed to open stream: No such file or directory` errors. Also, `b` reported that the project was successfully downloaded.

We need to:

1. Create the project-type folder if it doesn't exist (e.g. `layouts`), and
2. Not say `dl` was successful if it wasn't

**Comment by ghost** [comment]
Here's a PR: https://github.com/backdrop-contrib/b/pull/94

**Comment by indigoxela** [comment]
Confirmed, the PR fixes the bunch of notices when trying to download to a non-existent folder (multisite).

I've been testing with a theme.
