### ISSUE TITLE
Use CLImate

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#93]
I wonder if using something like [CLImate](https://climate.thephpleague.com/) would simplify `b`'s code/maintenance...?

It provides ways to define and parse arguments, format output, etc., so I'm thinking it might make our code more consistent (if nothing else).

**Comment by indigoxela** [comment]
Hm... an external library installable via composer...

I'm usually a fan of simple, standalone code wherever it makes sense.
Is it worth it? For just a little colored output it seems overdone to me.

**Comment by ghost** [comment]
I would include it manually in `b`'s repo (not use composer). I like simplicity too :slightly_smiling_face: 

I might try creating a branch that uses it, then we'll have a better idea/comparison if the code is too much, or if it reduces the code and makes it simpler...

**Comment by ghost** [comment]
I don't think this is going to work... I tried setting up a separate branch and adding CLImate into it (which was fine), but then trying to work out where/how to use CLImate instead of `b`'s custom hooks, etc. proved difficult. E.g. CLImate provides an easy way to handle and parse arguments (https://climate.thephpleague.com/arguments/) but doesn't support multiple commands or other things such as callbacks, bootstrap levels, etc. There may be a way to do it, but I'm not able to figure it out easily, so will leave this for now.
